- Gruntfile.js
Detect if a travis build is a pull requests and do not run sauce labs tests.
Signed the CLA Fyi
> Fix for Travis Builds on pull requests

- js/sendmessage.js
- js/storage/groups.js
This is untested, and probably shouldnt be merged until I get the droid<->bro compat good again.
> Replace all the refreshGroups stuff

- js/libtextsecure.js
- libaxolotl/protobufs.js
- libtextsecure/libaxolotl_concat.js
Fix undefined axolotl.protobufs.ProvisionMessage, referenced in
libaxolotl/protocol.js
> Fix provisioning flow

- js/libtextsecure.js
- libtextsecure/sendmessage.js
sendIndividualProto requires a timestamp.
> Fix textsecure.closeSession

- js/libtextsecure.js
- libtextsecure/sendmessage.js
> Sync outgoing individual and group messages

- js/libtextsecure.js
- libtextsecure/sendmessage.js
> Dont send group-update right before we quit the group

- images/save.svg
* OpenBSD amd64, Chromium 58.0.3029
Current picture of obscure floppy disk is unparseble for an average user. Some users are even sure there is no way to save an attachment. I guess an arrow pointing down to some flat thing is the most common way to represent Saving.
So here it comes:
> Replace unclear floppy image with down arrow as Save-As button

- main.js
- package.json
- test/manual.txt
- yarn.lock
We save four bits of data:
- Window size
- Window location
- Full-screen status
- Maximized status
To do this, we save a JSON file in the app settings directory. We use a new node module, `electron-config` to manage that for us.
> Remember window position between runs of the app

- stylesheets/_conversation.scss
- stylesheets/android-dark.scss
- stylesheets/manifest.css
* Fedora 26 Alpha, Chromium 58
Closes #1192. As discussed in #1217, this is the third pull request from me. I prefer a clean pull request over my previous work.
This pull request is tested in all 6 variants and is very easy to understand. I'd be glad, if it would be accepted.
Again, thanks for @scottnonnenberg to teach me in git a bit!
> Add effect for scroll-down-button

- js/views/message_view.js
Because we only attach AttachmentViews to the DOM when they fire their 'update' event, we were subject to a race condition. If that event fired after the final Message.render(), then it would be properly attached to the final DOM node. If it fired early, it would end up missing from the visible DOM entirely, attached to the old, discarded version of the message.
This change updates our handling of a second call to loadAttachments(). Instead of bailing out if we've been called before, we attempt to re-add our child AttachmentViews to the current DOM. But only if the 'update' event has been fired, and if their current parent node is not what is in the DOM.
I believe that this fixes #1215.
> Fix: Ensure that attachments are always rendered

- js/views/conversation_view.js
- stylesheets/_conversation.scss
- stylesheets/android-dark.scss
- stylesheets/manifest.css
A few changes:
- Spacing above and below was made consistent
- It was tightened up a bit, made a little more compact
- The highlight and shadow borders top/bottom were softened a bit
> A couple visual refinements to the last seen indicator

- protos/IncomingPushMessageSignal.proto
A number of changes here are just to make future diffs easier. The three commits starting with 'Add support for' are the ones with functionality changes.
> Update protos to match iOS

- appveyor.yml
> Remove node_modules cache to support pkg upgrades on feature branches

- main.js
This adds a simple minimum window size equal to the default starting width of the application.
> Enforce a minimum window size

- stylesheets/options.css
- stylesheets/options.scss
* Debian 9, Chrome 59.0.3071.86 64-bit
Changes the color of country names on the registration page to white since the background is white.
> Fix registration page readability issue

- js/libtextsecure.js
- js/models/conversations.js
- js/models/messages.js
- js/signal_protocol_store.js
- libtextsecure/libsignal-protocol.js
- test/keychange_listener_test.js
- test/storage_test.js
(targeted at the `combined` branch)
> Archive sibling sessions, getProfile instead of direct saveIdentity

- background.html
- test/index.html
Fixes #904, where letters in notification bubbles were being displayed in serif font on Antergos (Arch) OS, by specifying `font-family='sans-serif'` in the appropriate part of `background.html`.
// FREEBIE
> Specify font-family for identicon in notification

- _locales/en/messages.json
- js/background.js
- js/views/attachment_view.js
- js/views/conversation_view.js
- js/views/message_view.js
- stylesheets/_conversation.scss
- stylesheets/manifest.css
A number of small fixes - some visual, some logging...
> Small fixes

- background.html
- js/reliable_trigger.js
- test/index.html
- test/reliable_trigger_test.js
In the theme of bullet-proofing, we override Backbone's trigger to make all models, views, and clients using `Events` methods resilient to exceptions thrown by event handlers. After all, the data flow process is much more important than any mistake in the view logic.
> Reliable Backbone.trigger

- js/views/app_view.js
Otherwise the loading screen will show forever in some scenarios - like initial setup! Fixes #1358.
> AppView: Store initialLoadComplete value for late openInbox

- js/panel_controller.js
Stopgap until electron release.
* Windows 10 64bit.
> Update to work around flashing icon issue

- .gitignore
- .tx/config
So we can pull different translation resources from different branches.
// FREEBIE
> Add transifex config to git

- js/models/conversations.js
Found a number of 'Illegal buffer' errors in an Electron log submitted today. As far as I can tell, these same profiles are succeeding for me, so it's time to collect more data.
> Additional logging when we can't decrypt a user's profile

- _locales/da/messages.json
- _locales/fa/messages.json
- _locales/hr/messages.json
- _locales/pt_BR/messages.json
- _locales/pt_PT/messages.json
- _locales/ro/messages.json
- _locales/zh_TW/messages.json
> Update strings for da, fa, hr, pt_BR, pt_PT, ro, and zh_TW

- js/views/identity_key_send_error_view.js
- js/views/key_verification_view.js
> Eliminate $name$ in two places

- Gruntfile.js
- package.json
> Standardize artifact names

- _locales/en/messages.json
- js/models/messages.js
> i18n group updates

- js/backup.js
The previous fix didn't quite do it.
> Fully eliminate debug from imported data

- _locales/en/messages.json
- background.html
- js/views/app_view.js
- js/views/settings_view.js
- main.js
- preload.js
Add a setting in the themes section to hide the menu bar.
The menu bar is not needed in everyday use and might not fit in with signals dark theme.
The hidden menu bar can still be shown by pressing alt.
This basically exposes [win.setAutoHideMenuBar(hide)](https://electron.atom.io/docs/api/browser-window/#winsetautohidemenubarhide) to the user.
I did not check pass all the local tests because upstream master does not pass.
I get one failing test in spellChecker, that might be an issue with my computer.
> Add setting to hide menu bar

- .gitignore
- bower.json
- components/autosize/dist/autosize.js
- components/bytebuffer/dist/ByteBufferAB.js
- components/filesize/lib/filesize.js
- components/intl-tel-input/build/js/intlTelInput.js
- components/moment/min/moment-with-locales.js
- components/protobuf/dist/ProtoBuf.js
- js/components.js
- libtextsecure/components.js
The latest version of autosize has a fix for partial pixels causing height mismatches. I think this is why we had stack overflow-inducing infinite loops in autosize. And so, fixes #1492. Thanks to https://github.com/jackmoore/autosize/commit/5edede50943083a0a3d0781ba3c7494b8691dfcd
Also:
- Update gitignore to only exclude the root `/dist` folder
- Updated a couple other libraries with bugfix updates
> Update autosize, which should fix stack overflow error

- js/models/conversations.js
Had a little error in our error handling.
> models/conversation: Refer to proper error variable

- app/auto_update.js
There aren't any! And these checks fail with noisy errors in debug logs.
> Don't check for auto updates on linux

- js/libtextsecure.js
- libtextsecure/api.js
Don't expect a json response from this endpoint. It will only give you empty responses and exceptions. And sadness.
// FREEBIE
> Fix setSignedPreKey

- js/background.js
It's a race condition today, and we don't always win the race.
> Only start the app up when we've fetched all conversations

- js/models/conversations.js
I ran into an infinite loop in a conversation where there were errors showing up constantly on both sides (due to the bug https://github.com/WhisperSystems/Signal-Desktop/pull/1595 fixes) - each read receipt turned into an error on the other side, which caused a read receipt to be sent, and so on.
> Don't send read syncs or read receipts for messages with errors

- yarn.lock
https://github.com/electron/electron/releases/tag/v1.6.15
> Update to the latest Electron 1.6.x

- _locales/de/messages.json
- _locales/el/messages.json
- _locales/es/messages.json
- _locales/es_419/messages.json
- _locales/fa/messages.json
- _locales/hi/messages.json
- _locales/it/messages.json
- _locales/no/messages.json
- _locales/pt_PT/messages.json
- _locales/ro/messages.json
- _locales/ru/messages.json
- _locales/sl/messages.json
- _locales/zh_TW/messages.json
de, el, es, es_419, fa, hi, it, no, pt_PT, ro, ru, sl, and zh_TW
> Update strings for quite a few languages

- js/views/import_view.js
Learned about some of the bad things that can happen from the export work in the chrome app...
> Be resilient to thrown non-errors in import process

- js/backup.js
Previously we just waited 5 or 10 seconds, and if it didn't work out, then we just noted in the log.
Now we check for longer, and if any conversations are still not well-formed after that long, we fail the export.
> Poll for well-formed messages.json for five minutes, fail if not

- js/signal_protocol_store.js
> removeSignedPrekey: Be resilient to delete returning nothing

- js/backup.js
We've had a number of reports (https://github.com/WhisperSystems/Signal-Desktop/issues/1629, https://github.com/WhisperSystems/Signal-Desktop/issues/1624, https://github.com/WhisperSystems/Signal-Desktop/issues/1662) that the import process runs out of memory. It turns out that we were keeping all attachments for a given conversation in memory before saving the whole thing to the database at once. This change ensures that each attachment is handled serially: loaded, then saved to the database, and then the next attachment is handled.
We also had our very first import log with completely mysterious import errors: https://github.com/WhisperSystems/Signal-Desktop/issues/1765. So, this change also introduces proper error handling in our transaction or request `onerror` handlers.
> Import: Better onerror logging, save attachments serially

- aptly.sh
Tiny little update to `aptly.sh`
> aptly.sh: Instructions for pruning old packages from repo

- _locales/en/messages.json
Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1621
> Add some copy clarifying the import process

- js/models/conversations.js
- js/views/conversation_list_view.js
- js/views/inbox_view.js
> Remove conversation from left pane on 'delete messages'

- _locales/en/messages.json
- js/models/conversations.js
- js/models/messages.js
> Properly localize group changes

- README.md
Update informative pages only, hence not tested on devices
Update informative pages only, hence not tested on devices
Simplify informative github pages to use updated Signal websites
> Update readme.md to use signal.org URLs

- js/libtextsecure.js
- libtextsecure/sendmessage.js
> Move sync messages to silent = true

- aptly.sh
artful and xenial. Sadly, this appears to double the upload time for a new build. :0(
Fixes #1809
> aptly.sh: support for current and previous ubuntu versions

- package.json
- yarn.lock
> Support the latest phone number formats via libphonenumber

- package.json
- yarn.lock
It's the latest (production) version of Electron: https://github.com/electron/electron/releases/tag/v1.7.10
> Update to Electron 1.7.10

- CONTRIBUTING.md
- README.md
A few more tweaks to the readme and contributing guidelines.
> Readme: big install, Contributing: mention Next Steps project

- app/config.js
> Harden production against NODE_ENV environment variable

- CONTRIBUTING.md
- Gruntfile.js
- README.md
- _locales/en/messages.json
- app/auto_update.js
- background.html
- bower.json
- js/signal_protocol_store.js
- js/views/install_view.js
- libtextsecure/message_receiver.js
- libtextsecure/websocket-resources.js
- main.js
- package.json
- test/index.html
Fixes the 'build unknown' icon currently showing in the readme, updates every pointer to support, the twitter account, the main website, and the GitHub repo location.
> Big update to new signal branding

- _locales/en/messages.json
When the app is auto-updating, it doesn't say that restarting will only restart the app. I was afraid that it would restart the entire system.
> Clarify message when auto-updating.

- js/models/conversations.js
- js/signal_protocol_store.js
Putting the `result`-handling logic behind an `if` is not constant time!
> Make our binary comparisons constant time

- libtextsecure/libsignal-protocol.js
Captures the three recent PRs merged in that project. Fixes #2044.
> Update to libsignal-protocol-javascript v1.3.0

- .eslintignore
- app/menu.js
- js/.eslintrc
- js/modules/.eslintrc
- js/views/attachment_view.js
- js/views/conversation_search_view.js
- js/views/inbox_view.js
As prep for ‘UX Improvements’ work, I applied ESLint auto-fixes. This was done in a separate branch / PR as previously discussed to reduce churn and simplify review of actual changes.
Autofixes are covered in first four commits and manual adjustments can be reviewed here: https://github.com/signalapp/Signal-Desktop/compare/3044103...ux-improvements-lint
> Auto-fixes: UX Improvements

- js/views/inbox_view.js
Fixes #2125 No longer do multiple settings windows stack upon one another. This quick check to see if one is already open prevents multiples.
Tested via keyboard shortcut and menu item on macOS 10.13.3
> Fix #2125 Prevent multiple settings modals

- background.html
- js/views/react_wrapper_view.js
- styleguide.config.js
Turns out its name wasn't correct, and it wasn't included everywhere it was needed yet anyway.
> Rename file for Whisper.ReactWrapperView

- README.md
Fix beta install instructions for debian-based linux
> Fix beta install instructions for debian-based linux

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- package.json
- ts/components/Lightbox.md
- ts/components/LightboxGallery.md
- ts/components/conversation/Message.md
- ts/components/conversation/Quote.md
- ts/components/conversation/media-gallery/EmptyState.md
- ts/components/conversation/media-gallery/MediaGallery.md
- ts/components/utility/BackboneWrapper.md
- ts/styleguide/ConversationContext.md
That's pretty much it! A couple small fixes were required for the issue template to keep it well-formed.
> Turn on prettier support for markdown files, update all files

- CONTRIBUTING.md
Edit our developer setup instructions to cover Windows 7. Based off #2320.
> Document Windows 7 Developer Setup

- CONTRIBUTING.md
- _locales/en/messages.json
- js/views/message_detail_view.js
> Document Translations Setup + Remove Unused Strings

- js/expiring_messages.js
- js/models/conversations.js
- js/models/messages.js
- js/modules/privacy.js
- js/views/conversation_view.js
- test/modules/privacy_test.js
> Improve Logging For Disappearing Messages

- stylesheets/android-dark.scss
Fixes #2325 , updating color on hover. Tested manually with Mac OS as style-based.
> Update hover color for horizontal dots in android dark theme

- _locales/pt_BR/messages.json
- _locales/ru/messages.json
- _locales/sv/messages.json
> Update translations for week of 5/7

- js/background.js
- js/notifications.js
- js/read_syncs.js
> Notification Improvements

- CONTRIBUTING.md
Updated CONTRIBUTING.MD for an additional Windows 7 requirement for archived SDK's, specifically requested is the Windows 8.1 SDK https://go.microsoft.com/fwlink/p/?LinkId=323507
> Add another Windows 7 requirement for a dev setup

- ts/components/conversation/Emojify.tsx
- ts/components/conversation/MessageBody.md
> Update React-based emoji handling to fix skin tone modifiers

- js/models/conversations.js
- js/views/file_input_view.js
> Show generic file icon if we fail to make attachment thumbnail

- about.html
- preload.js
Fixes https://github.com/signalapp/Signal-Desktop/issues/2463
> Restore version/environment details to about window

- stylesheets/_conversation.scss
- ts/components/conversation/ContactDetail.tsx
Fixes https://github.com/signalapp/Signal-Desktop/issues/2397
> Fix width of message detail screen

- js/views/conversation_list_view.js
Fixes #2440 
Manual tests done:
* Scroll down the conversations list, pick an empty conversation and send a message in it.
Result : Conversation goes to the top and is scrolled to.
* Remove the added message
Result : Conversation goes back to its place, and is scrolled to.
* If conversation is in the first conversations of the list and scrolldown is at the top, nothing happens.
Operating system : Linux Mint 17 Qiana
Notes:
* test `should work` from `spellcheck_test.js` fails (before and after changes) do you have any idea where this could come from ?
> Auto-scroll to selected conversation when reordering them

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
I updated a few legacy GitHub links, fixed a couple of typos, and rephrased a few sentences.
> Minor documentation cleanup.

- .github/PULL_REQUEST_TEMPLATE.md
https://www.transifex.com/liliakai/signal-desktop/ is no long available.
> Fix Broken Link to Signal Desktop Transifex Project in PULL_REQUEST_TEMPLATE.md

- js/views/conversation_view.js
- stylesheets/_index.scss
- stylesheets/_modules.scss
- stylesheets/_theme_dark.scss
- ts/components/Lightbox.tsx
- ts/components/conversation/media-gallery/MediaGallery.md
- ts/components/conversation/media-gallery/MediaGridItem.md
- ts/components/conversation/media-gallery/MediaGridItem.tsx
- ts/components/conversation/media-gallery/types/Message.tsx
Three changes:
1. Fix MediaGallery handling of videos - show thumbnail and overlay
2. Dark theme: Brighten icons on image overlay for visibility
3. Lightbox: Play video on open, play/pause on click of video itself
> Video: Show properly in Media gallery, autoplay, metadata icon overlay

- permissions_popup_preload.js
Fixes https://github.com/signalapp/Signal-Desktop/issues/2551
> Fix permissions popup; add needed function on window

- README.md
Added:
[![Build Status](https://ci.appveyor.com/api/projects/status/github/signalapp/Signal-Desktop?branch=master&svg=true)](https://ci.appveyor.com/project/Signal-Desktop/signal-desktop)
> Adding Appveyor SVG Status Badge

- .github/ISSUE_TEMPLATE.md
Uppercasing some titles, Adding iOS/Android Specific URLs, etc.
> Issue Template, Small Edits

- .github/PULL_REQUEST_TEMPLATE.md
The current link leads to a 404 (try for yourself above ;-))
> Update Transifex link in pull request template

- libtextsecure/account_manager.js
- libtextsecure/test/account_manager_test.js
Ran into this on the Contributors guidelines setting up the development env.
registerSingleDevice does not pass a deviceName, so it fail every time.
> Ensure encrypting device name does not die on empty device name

- libtextsecure/sendmessage.js
*This pull request does not introduce any behavioural changes. Only the code correctness and readability is affected.*
While debugging I noticed that the arguments are not properly mapped when instantiating MessageSender:
in background.js:
```js
window.textsecure.messaging = new textsecure.MessageSender(
USERNAME,
PASSWORD
);
``` 
in sendmessage.js line 892:
```js
textsecure.MessageSender = function MessageSenderWrapper(
url,
username,
password,
cdnUrl
) {
const sender = new MessageSender(url, username, password, cdnUrl);
```
So basically `USERNAME` and `PASSWORD` are passed in as `url` and `username` in MessageSenderWrapper, then later remapped as username and password in MessageSender contructor:
```js
function MessageSender(username, password) {
```
sendmessage.js line 143.
Note: I …
> Fix arguments in MessageSenderWrapper

- ts/components/conversation/ContactName.tsx
Just add `dir=auto` attribute to contact's name container, to support RTL languages contacts' name.
> Add RTL support for contact's name

- package.json
- preload.js
- yarn.lock
* [ X ] I have read the [README](https://github.com/signalapp/Signal-Desktop/blob/master/README.md) and [Contributor Guidelines](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md)
* [ X ] I have signed the [Contributor Licence Agreement](https://signal.org/cla/)
* [ X ] My contribution is **not** related to translations. _Please submit translation changes via our [Signal Desktop Transifex project](https://www.transifex.com/signalapp/signal-desktop/)._
* [ X ] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [ X ] My changes are [rebased](https://medium.freecodecamp.org/git-rebase-and-the-golden-rule-explained-70715eccc372) on the latest [`development`](https://github.com/signalapp/Signal-Desktop/tree/developm …
> Adding right click listener for URLs, and Text Selections.

- app/dock_icon.js
- app/tray_icon.js
- main.js
Fixes #2012 
Manual tests done:
* Run `yarn start --use-tray-icon` then close the Signal window.
Result: icon is hidden from the dock and from the cmd+tab switcher, tray icon is available to reopen the window.
* Open the window using the tray icon.
Result: app shows up on the dock and in the cmd+tab switcher.
* Run `yarn start` while the previous instance is running and is hidden.
Result: newly started instance exits, previously started instance opens its window and app shows up on the dock.
Operating system: macOS Sierra 10.12.6
> MacOS: Hide from Dock when application is in tray

- package.json
In commit 01a91d2cc1, the `build-release` command was reverted from the change in commit 851c1a0e47413. However, a `&&` operator was left by mistake which means the npm invocation would not see the `SIGNAL_ENV` environment variable. This caused the build to fail on my machine (Linux).
> Restore build-release command properly

- _locales/en/messages.json
Fixes typos in `messages.json`.
> Fix typos in messages.json

- js/models/messages.js
- ts/components/MessageSearchResult.md
- ts/components/MessageSearchResult.tsx
Fixes #3762 
Tested manually to ensure that search results still render properly using the sent at timestamp 
Tested on OS X 10.15.1
> Fixes #3762: Adjust search results to show the message sent time

- README.md
> License Year Update

- CONTRIBUTING.md
In the contributing doc, mention the `git-lfs` requirement on macOS.  It's likely that these three issues (#3609 #2929 #2916) all were caused by the user missing git-lfs. Lacking this results in a very confusing error message when trying to install the node requirements.
When getting started as a contributor on macOS, if you don't have `git-lfs` installed, then when you run `yarn install --frozen-lockfile` it'll fail with the error message `error An unexpected error occurred: "Unexpected end of data"`.  This is because when yarn runs `git clone --depth=1 -q -b updates https://github.com/scottnonnenberg-signal/node-sqlcipher.git` it fails if git-lfs isn't installed.
Oddly, I tried this on an Ubuntu machine where I ensured that the git-lfs wasn't installed, and things worked fine.  Seems …
> Mention the `git-lfs` requirement on macOS in the contributor docs

- ts/components/hooks.ts
Previously the focus event was not being passed to `CompositionInput`, this means that in some cases the emoji autocomplete was unable to activate due to lost of focus and leaving `Editor` in a state where it cannot detect proper text selection.
This commit ensures that `CompositionInput` receive focus.
Fixes #3932
> Fix focus on CompositionInput

- find_broken_perms.sh
- fix_broken_perms.sh
- [ X] I have read the [README](https://github.com/signalapp/Signal-Desktop/blob/master/README.md) and [Contributor Guidelines](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md)
- [ X] I have signed the [Contributor Licence Agreement](https://signal.org/cla/)
- [X ] My contribution is **not** related to translations. _Please submit translation changes via our [Signal Desktop Transifex project](https://www.transifex.com/signalapp/signal-desktop/)._
- [ X] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
- [X ] My changes are [rebased](https://medium.freecodecamp.org/git-rebase-and-the-golden-rule-explained-70715eccc372) on the latest [`development`](https://github.com/signalapp/Signal-Desktop/tree/development) …
> remove old unused shell scripts

- about.html
- package.json
Removed unnecessary scrollbar on the about window, fixes #4139.
> Removed scrollbar on about page

- _locales/en/messages.json
Fixes some typos in source `messages.json`.
> Fix some typos in messages.json

- CONTRIBUTING.md
Added paragraph with the request to close (exit) the prod + dev apps, as it is crucial for the success of the staging data population process.
Improve Staging part in CONTRIBUTING.md:
- According to issue #2164, both dev + prod apps should be closed in order for the process to be successful.
- Adding this line will hopefully help other forkers who struggled like I did :)
> Improve instructions for the "staging environment" part in CONTRIBUTING.md (Issue #2164)

- _locales/en/messages.json
- app/attachments.js
- libtextsecure/test/blanket_mocha.js
- test/backup_test.js
- test/blanket_mocha.js
> Fixing spelling errors

- app/menu.js
- test/app/fixtures/menu-mac-os-setup.json
- test/app/fixtures/menu-mac-os.json
Fixes #4631
Adds `⌘ ⇧ 0` shortcut to Window -> Show
> MacOS – Add shortcut for Window -> Show

- README.md
Right now the README suggests folks log feature requests in the repo. just adding a little more info to point them to discourse instead (as per recent issue closures and the issue template).
> guide feature requests to community forum in README

- ts/background.ts
MacOS Messages and WhatsApp (amongst other messaging apps) use this Cmd + Shift + [/] to switch between convos.  Would be great to have that in Signal as well.
MacOS Messages and WhatsApp (amongst other messaging apps) use this Cmd + Shift + [/] to switch between convos.  Would be great to have that in Signal as well.
I tested this locally by extracting the asar.app and making those changes and then running the app.  I have not written any tests.  I'm completely open to having this change without my name associated with it.
> Add keyboard shortcut to match other MacOS Chat Apps

- stylesheets/_modules.scss
Hello all, it's my first contribution. I've decided to start with a small fix :)
This PR fixes a bug with blinking message options when hovering a mouse horizontally between the message and its options.
**To reproduce:**
1) Hover a mouse over a message
2) Move horizontally directly over the message options
**Expected results:**
3) Message options are displayed consistently when moving a mouse from the message
**Actual results:**
4) Message options disappear for a split-second when the mouse is between the message and the options.
**Before:**
https://user-images.githubusercontent.com/7289999/105645950-48d92980-5e9d-11eb-9683-af56a37e0128.mov
**After:**
https://user-images.githubusercontent.com/7289999/105645952-4d9ddd80-5e9d-11eb-96e9-956307882f53.mov
Tested on macOS. No additional tests …
> Fix blinking message options when hovering a message

- ts/types/MIME.ts
Updates the call signatures of the `MIMEType` predicate functions per conversation on #4711 (there is still more discussion on improving the `MIMEType` support in our app - so this does NOT close this issue)
No new tests added (no need to change tests with the given changes).
> Adjusting MIMEType Predicate Signatures

- CONTRIBUTING.md
Related: #4995
See changes and corresponding issue. Right now the contributing.md does not mention `git-lfs` and `yarn install` fails with a cryptic error if it is not installed / initialized.
> Update CONTRIBUTING.md: mention git-lfs

- ts/components/emoji/EmojiButton.tsx
Fixes #4932 .
Tested manually on Arch Linux (kernel version 5.11.11-arch1-1).
Before:
After:
> set positionFixed in emoji Popper to prevent flipping

- background.html
- test/index.html
Fixes the HTML ID for "step 2" in `background.html` for the `clear-data` template, which was incorrectly labeled as `step3`. I don't believe this ID was used for anything, so it wasn't causing any problems, and I don't believe this change will affect anything. Just noticed it while exploring other code and figured it should be corrected.
> Fix HTML ID of step for `clear-data` template

- .github/PULL_REQUEST_TEMPLATE.md
> Update link to Git rebase tutorial

- CONTRIBUTING.md
> Update CONTRIBUTING.md (python version)

- debug_log_preload.js
- js/debug_log_start.js
Fixes #4662.
Manually tested, didn't see anywhere with existing tests to add this to. Tested solely on MacOS 10.15.7.
> Respect system theme in debug log modal

- settings.html
Ensures that the settings window updates the theme when the system theme is changed. Simple change, uses the same mechanism as the permissions popup.
> Have settings window update on theme changes

- ts/components/StopPropagation.tsx
Stops the propagation of `keyDown` event in `StopPropagation`. This ensures a key click event on a reaction emoji properly reacts and does not open the image.
For testing, I tested reacting on text messages and image messages using the `space bar` and `Enter` key. Additionally, I ensured the other instances of `StopPropagation` also work as expected. I did not write any new tests. I performed development and testing on Linux 64-bit (Pop!_OS 21.04, GNOME 3.38.5).
Fixes #5551.
> Fix Emoji Reactions for Image Messages

- _locales/en/messages.json
- ts/components/leftPane/LeftPaneArchiveHelper.tsx
When you want to see archived conversations by going **Profile > View Archive**, it seems like helper text doesn't really pointing anything, so if there are no archived converstations; we basically want to see a text like **"No archived conversations."** which would makes sense to see.
> Improve archive helper text

- .github/workflows/backport.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- - - - - - - - - -
This PR bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL, no longer receives security updates):
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/cache` can be [found here](https://github.com/actions/cache/releases)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
- Releases for `actions/upload-artifact` can be [found here](https://github.com/actions/upload-artifact/releases)
This PR also fixes an invalid runner name: `macos-11.0` to `macos-11`, see [GitHub workflow docs here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#su …
> Update GitHub Actions

- stylesheets/_global.scss
Make checkboxes dark in a dark theme. I tested it with Signal Desktop for macOS.
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
</details>
> Make checkboxes dark in dark theme
