signalapp/Signal-Desktop

Gruntfile.js

Revert "Do not run saucelabs tests on pull requests because they will fail"
This reverts commit 7b851ba548ea8ab9774b59a6adcf5e27c9254360.
This seemed like a good idea at the time, but it prevents tests from
being run on PR's made from branches within our own fork.(*) Also, in
hindsight, I find that the "merge with caution" alert banner is an
appropriate adornment for PR's which have not been able to run the
saucelabs tests due to their alien origin.
(*) Like this one

Re-enable sauce for PR's

---

js/libtextsecure.js
libtextsecure/api.js

Use only the finest, hand-crafted, artisanal XMLHttpRequests. Allows for some simplification of success/error callbacks.
Prior to this change, attempting to use any libtextsecure server api function without including jquery on the same page would result in a crash.

Remove libtextsecure's jquery dependency

---

Gruntfile.js
js/background.js
js/inbox_controller.js
js/index.js
js/libtextsecure.js
js/options.js
js/register.js
js/views/conversation_view.js
js/views/message_detail_view.js
libtextsecure/api.js
libtextsecure/axolotl_wrapper.js
libtextsecure/crypto.js
libtextsecure/helpers.js
libtextsecure/sendmessage.js
libtextsecure/storage.js
libtextsecure/storage/devices.js
libtextsecure/storage/groups.js
libtextsecure/storage/user.js

This requires reset for a number of reasons.
See individual commits for more information, but essentially this refactors all the storage stuff in libtextsecure so that it is forward-compatible (ie the parts that are still over-complicated can be deleted entirely with no adverse consequences), as well as providing a simple interface which can replace localStorage if its overridden.

Refactor storage in libtextsecure

---

js/key_worker.js
js/libtextsecure.js
libtextsecure/storage/devices.js

Last usage of the `returnIdentityKey` argument was removed in 8b9a16852.

Remove unsued argument from getDeviceObject

---

js/chromium.js
js/panel_controller.js

As discussed in similar issue there: https://github.com/GoogleChrome/chromedeveditor/issues/1023 - it is not possible to add onClosed event listener on an 'abstract' current window property, it needs to be set on the particular window instance instead.
Before that change, the clean up function was never actually called, because the listener was never properly attached. That was probably the reason of existence for "panel isn't actually open ... and so we try again." code that was executed if the previous window wasn't cleaned up properly (so actually every time). This code is no longer needed, I guess, as the windows are now cleaned up properly.

Fix for conversation & inbox windows closing callbacks never called.

---

background.html
js/views/conversation_view.js
js/views/message_view.js

Line breaks can now be insterted into message box using Shift+Enter or Alt+Enter. Messages with new lines are properly displayed in the conversation view (but only there, to keep inbox clean). The template was modified to allow HTML, but the message itself is sanitized before new line handling is run.

Allow line breaks in messages. Closes issue #291

---

background.html

Generates a simple clear element when typing. Closes https://github.com/WhisperSystems/Signal-Desktop/issues/420 
Will work in all HTML 5.0 compatible browsers.
// FREEBIE

Change input type of search field to "search"

---

stylesheets/_conversation.scss
stylesheets/manifest.css

Resolves #416
Before:
After:
// FREEBIE

Let container-div fit in key-verification-window

---

_locales/en/messages.json

Fixes two strings that didn't use the term _linking_. As we know that's correct term to use in this multi-device context ([1](https://github.com/WhisperSystems/Signal-Android/issues/3830), [2](https://github.com/WhisperSystems/Signal-Android/pull/3831), [3](https://github.com/WhisperSystems/Signal-Android/blob/759f9d80169bf8d6de7d973366e4bbc5cc890900/res/values/strings.xml#L392)).

Fix two strings that didn't use term 'linking'

---

stylesheets/_global.scss
stylesheets/manifest.css

Remove the 1px gray border around the window. This allows to the window to integrate seamlessly with custom window managers which use the background color for the titlebar.
The end result looks like [this](http://i.imgur.com/0yPtayt.png).

Remove gray border around window

---

stylesheets/_index.scss
stylesheets/manifest.css

bug introduced in: 0569d4c
This z-index property was previously to ensure the avatar floated above message
bubbles, but the message bubbles always have enough left margin so this
property is not needed.
fixes #650

Fix avatar floating over debug log

---

js/views/message_detail_view.js

* W10
Fixes #954.
before:
after:

Messagedetailviewtimestampfix

---

js/views/file_input_view.js

* Windows 10, Chrome 55
* Arch Linux, Chromium 52
This pull request adds copy and paste support of images to the input box of conversation windows.
Tested this on two different computers with two different browsers. Tested by copying and pasting an image, then some text, then a different image, then different text, then another different image, then another different text.

Add copy and paste for images

---

CONTRIBUTING.md

Small change to clarify where the TextSecure server URL should be updated to the staging value in local builds. 
Ran into this one when building a local version of the iOS app for testing desktop linking in #1097. 
It looks like the Android variable has been updated from `TEXTSECURE_URL` to `SIGNAL_URL` (https://github.com/WhisperSystems/Signal-Android/commit/ae40715526aa0fbad583783be63115bb46b1c2c8#diff-c197962302397baf3a4cc36463dce5eaR179) and the iOS counterpart is named `textSecureServerURL`.
Should the `textSecureWebSocketAPI` value on iOS be updated as well in this case? FWIW I didn't see a counterpart to that in the Android repo.
FREEBIE

Update TextSecure Staging URL instructions

---

js/views/inbox_view.js
stylesheets/_index.scss
stylesheets/_ios.scss
stylesheets/_variables.scss
stylesheets/android-dark.scss
stylesheets/manifest.css

* macOS 10.12.13 Chrome 57.0.2987.110 (64-bit)
Only one commit, so I'll just paste the commit message below. The only thing I'd add is that I tested it manually with ltr and rtl text and switching between them, and that all seemed to work great. Using the esc button to clear text works too (I saw this was an issue with the solution proposed in #983). I didn't write any tests because I didn't see any UI tests generally/know where/how to write  them. Let me know if I ought to (or if there are any other changes) - this is my first contribution to Signal, or any open source project, so I'm very receptive to any feedback and want to learn!
This makes the "x" in the search bar always visible when there is
text in the search box, even if the mouse is not …

Make search clear button ("x") persist w/o hover

---

.gitignore
background.html
bower.json
components/filesize/lib/filesize.js
js/components.js
js/views/attachment_view.js
stylesheets/_android.scss
stylesheets/_conversation.scss
stylesheets/_ios.scss
stylesheets/android-dark.scss
stylesheets/manifest.css
test/index.html
test/views/attachment_view_test.js

Fixes #1150. See below screenshots. Existing transparency and hover behavior was maintained, which means that any text included in the message will be a slightly different color until the attachment is hovered over.

Bring file attachments on-theme

---

components/emojijs/demo/emoji.css
js/emoji_util.js
stylesheets/manifest.css
test/emoji_util_test.js
test/index.html

Fixes #1147. Matches scaling algorithm used on the Android client, implemented in this PR: https://github.com/WhisperSystems/Signal-Android/pull/6531
Before:
After:

Jumbomoji support matching Android support

---

js/models/messages.js

Check for early read receipts for an incoming messages *after*
processing the expireTimer on that message. Then we can set
expirationStartTime appropriately if an early receipt is found.
Closes #950

Early read receipts should start expiration timers

---

_locales/en/messages.json
js/views/conversation_view.js

Block sending to left groups in the same way we block sending when the contact is on our block list or the client is too far out of date.
Before:
After:

Conversation view blocks sending to left groups

---

js/libtextsecure.js
libtextsecure/sendmessage.js

Previously 'Reset Session' would send an end session message but not sync it because the mobile clients didn't handle that flavor of sync message correctly.
I believe Android and iOS have both been fixed now.
Closes #658

Sync end session messages

---

js/models/messages.js

When leaving a group on mobile, we sync the group quit message to desktop, but
we weren't marking the conversation left.

Mark groups left on synced "You left the group"

---

package.json
preload.js
test/index.html
test/spellcheck_test.js

I initially thought this was a native module issue, but it turns out to be an asar issue, wherein the spellcheck module can't read dictionary files from an asar. While I was here I added a minimal test for spellchecking and also slimmed down our asar size by excluding ~1MB (uncompressed) of hunspell source code.

Fix Spellcheck on Windows and Linux

---

js/views/conversation_view.js

When we get read receipts, a conversation's in-memory messages can get out of date with the database. This means that we'll have messages with `unread = 1` in the collection, but the overall conversation `unreadCount` is zero. For now, we won't show the last seen indicator in this case. In the future, we'll want to prevent these kind of out-of-sync errors.

Ensure that we never show last seen indicator if count is zero

---

stylesheets/_index.scss
stylesheets/android-dark.scss
stylesheets/manifest.css

// FREEBIE
* OpenBSD amd64, Chromium 58.0.3029
Two layered X icons  are displayed. This PR is to fix #1136.

Fix duplicate x icon (cancel) on active search field

---

_locales/en/messages.json
stylesheets/_conversation.scss
stylesheets/manifest.css

A number of small changes
* Show a pointer cursor on safety number change notification, to show that it can be clicked
* Add 'click to verify' to the text shown there
* Add ':' to the text shown on the safety number screen
* Limit the width of the safety number box, to force 3x4 layout
* Center the safety number box

Safety number UI tweaks

---

Gruntfile.js

Without this file, clients would be stranded on the current version forever.
This change extends release-test to verify its presence in a packaged build.
// FREEBIE

Add release test for auto updater config

---

js/background.js
manifest.json

* Arch Linux - Chrome Version 58.0.3029.81 (64-bit)
This change adds support for opening the inbox via a user-defined shortcut (defaulting to Alt+S, if available) and fixes #1134.

Add support for opening the inbox via a keyboard shortcut - fixes #1134.

---

js/models/messages.js

Resolves situation with read receipts not setting messages as read if conversation is already loaded. Why? The default `fetch()` call does pull the latest information from the database, but it doesn't eliminate keys which have been removed - it only overwrites the current attributes with the pulled attributes. Our version drops all local data in favor of database data.
Also, a bonus to ensure that our conversation fetches don't result in infinite loops.

Replace Backbone.fetch with our own; overwrite local data with db data

---

js/views/conversation_view.js
js/views/last_seen_indicator_view.js
test/manual.txt
test/views/last_seen_indicator_view_test.js

A couple changes to last seen indicator/scrolling:
- If you've scrolled up in a conversation and switch to another window (leaving the conversation active but the window loses focus), we will preserve your scroll location even if new messages come in. This is different from leaving the conversation within the app and coming back, which will force you to see the last seen indicator.
- If you're above the last seen indicator, the first click of the scroll down button will take you to the last seen indicator, with the oldest new messages. Once you're there, a second click will take you to the bottom of the conversation, with the very newest messages.
- Today the last seen indicator is dismissed when new messages arrive, to ensure that it doesn't stick around for a long time in an active …

Scrolling and last seen indicator UX tweaks

---

js/models/conversations.js
js/models/messages.js

Occasionally you can see the last seen indicator in a totally inappropriate place. Say, for example, with the number 1 in it, but five messages up. Or higher. And it will continue to do that until you restart the app.
This is because we had a race condition. We would mark the message as unread in the database, but it wouldn't be in our message collection. So it would sit there, unread, until restart. These changes catch that, sync state with the database, and start all the timers that are supposed to start when a message is unread. This might fix some of the problems we have with disappearing messages not disappearing.
Along with the fix, this change adds some console logs to help us determine whether this ever happens to people in the wild.
Tested this with a script that sent message …

Fix race condition: Pull from database after add to conversation

---

js/views/conversation_view.js

Sadly a [recent commit](https://github.com/WhisperSystems/Signal-Desktop/commit/9de384f3b8816631dc7ab1843187b55cfb860f68) regressed the "don't scroll on focus" work I merged earlier today. This fixes that. The [new behaviors described in that pull request](https://github.com/WhisperSystems/Signal-Desktop/pull/1197) now truly apply. :0)
Bonus: We don't get rid of the last seen indicator quite as aggressively.

Fix: Don't scroll to last seen indicator on focus

---

js/views/conversation_view.js
js/views/message_list_view.js

A bit of cleanup in our 'is the conversation at the bottom?' code, as well as a little bit of wiggle room. We consider the 30px of space at the bottom of the conversation to be 'at the bottom' so users who are 'close enough' at the bottom of the conversation won't get marooned in history.

30px at bottom of conversation considered 'at the bottom'

---

js/models/messages.js

Negate the flag marking the group as left. Fixes #1207.
This bug was introduced by the combination of app-level left group blocking in cfe0c77 and a fix to left-group state tracking in 80bfe18.

Fix being re-added to a group you previously left

---

js/views/conversation_view.js

With the recent changes to scrolling behavior, the 'load more messages' scenario was left behind. This work attempts to keep the scroll position exactly where it was when you initially made the scroll request. There's a little bit of flashing I'd like to get rid of at some point, but it does faithfully maintain the scroll position based on my testing.

Update the scroll position when 'fetch more messages' is complete

---

background.html
stylesheets/_android.scss
stylesheets/_conversation.scss
stylesheets/_global.scss
stylesheets/_index.scss
stylesheets/_ios.scss
stylesheets/android-dark.scss
stylesheets/manifest.css
test/index.html

- The last seen indicator now spans the full conversation, with subtle shadow highlights above and below.
- Scrollbars now overlap the content of the conversation, allowing last seen indicator to touch the right edge of the window. This update to the scrollbars was also applied to the conversation list on the left side.
- The iOS and Android conversation background is now `#eee` instead of white, which meant that the outgoing messages (Android) and incoming messages (iOS) had to be updated for contrast. They now have white backgrounds.
- Similarly, the scroll down button needed more contrast, and its background is now white in light themes.

Visual refresh of last seen indicator

---

js/views/attachment_view.js
js/views/message_view.js

Fixes #1213, introduced by recent changes to re-fetch data from IndexedDB.
This change makes `MessageView.render()` idempotent. Our previous technique for loading attachments resulted in a new `AttachmentView` added for every call to `render()`. We now only add attachments the first time. This okay because messages are immutable, therefore attachments don't change.
Also: A quick fix of a typo in an i18n message.

Fix: attachments rendered multiple times

---

js/views/whisper_view.js
stylesheets/android-dark.scss
stylesheets/manifest.css

* Chromium 58.0.3029.81 on Arch Linux
tl;dr: Fixed the problem with the white confirmation box.
I thought, this would be pretty easy as all the other enhancements for the dark theme. But it wasn't just changing something in the sass files but changing the position where the box become positioned in the main html. It was not affected by the sass rules of the dark design, because it was generated directly under the root body element. This actually took me some time to realize as the dialog wasn't generated in its own view but in a function of the inbox view, too. I just wanted to quickly document this here because it might come in handy again in further work with bug fixing and developing the application multi-themed.

fixed #1163, dark theme flaw

---

js/views/conversation_view.js

Sadly, some sort of slip in the editor caused a key bit of code to be left out of https://github.com/WhisperSystems/Signal-Desktop/pull/1222. Sadly, linting didn't find it because it ended in `.`, and it skated under the review radar. :0/

loadMoreMessages: Fix broken reference to this.view.outerHeight

---

js/models/messages.js
js/views/message_view.js

While investigating #1138, I discovered and fixed a couple things.
First, because we re-render messages more often now, we were missing hourglass icons on incoming messages. The `TimerView`'s `el` was not attached to the new DOM as generated by `MessageView` re-renders.
Also: For short-expiring messages, we would schedule a huge number of `setTimeout` callbacks. This introduces a `Math.max()` call so we don't update the hourglass more often than 500ms. We also ensure that we don't continue to update after the message is expired.
Lastly, we remove a couple unused bits of code:
- initialize doesn't need to call update because `MessageView.renderExpiring()` calls it immediately
- we don't need the className because that's already present on the `el` it attaches to, part of the …

Fix for missing hourglass on incoming messages, reduce callbacks

---

js/models/conversations.js
js/views/conversation_view.js

It's no longer guaranteed to be true that you've read all messages when you send a message. If you're scrolled up in a conversation, you may not have read all messages. Setting the `unreadCount` to zero is not good - it prevents the user from marking any of their existing messages as unread until something else happens, like receiving a read receipt or new message.
Also: `ConversationView.markRead()` now marks all messages as read when at bottom. To handle the same 'not quite at the bottom' case that our 30px buffer gives us for scrolling, we use the same `atBottom()` method to determine whether we should mark everything unread. Saves the effort and potential missed messages (due to partial pixels, etc.) of searching for visible messages.

Conversation.sendMessage: Don't set unreadCount to zero

---

js/models/conversations.js
js/models/messages.js
js/read_receipts.js

On read receipt, we:
1. We mark as read everything older than this message - to clean up old stuff still marked unread in the database. If the user generally doesn't read in the desktop app, so the desktop app only gets read receipts, we can very easily end up with messages never marked as read (our previous early read receipt handling, read receipts never sent because app was offline).
2. We queue the job because we often get a whole lot of read receipts at once, and their markRead calls could very easily overlap given the async pull from DB.
3. We also disable read receipts for any message marked read due to a read receipt. That's a notification explosion we don't need.
4. We no longer restrict `Conversation.markUnread()` to situations where its `unreadCount` property is above zero. …

Update message history on read receipt

---

_locales/en/messages.json
background.html
js/views/conversation_view.js
stylesheets/_conversation.scss
stylesheets/manifest.css

Rel: #285 #1049
* Chromium 58.0.3029.81 on Arch Linux

Add message length warning for sending messages to android clients

---

stylesheets/_conversation.scss
stylesheets/manifest.css

On Linux, where Helvetica Neue is not installed, we fall back to Times New Roman for the Last Seen Indicator. Removed - we didn't need Helvetica Neue anyway.
The oldest message in a conversation was 0px from the top of the window. Now has proper padding.

Visual tweaks: Fix last seen font, padding at top of conversation

---

js/views/message_view.js

Fixes #1242.
With the reliable repro provided in #1242, I was able to very clearly see that it was a problem of missing event handlers when we moved the `AttachmentView`'s `el` from one parent to another. I thought I had reproduced this issue before, but apparently not when I thought I did, or not when it counted. There y'are!

Use setElement to ensure that re-parented AttachmentViews listen for events

---

manifest.json

Verified via a new profile that the Alt+S shortcut isn't put in place on new installs, but I suspect that it won't fix the situation for users who have already installed older builds.
Fixes #1259. And those still commenting in #1134 will want to know about this.

Remove default Alt+S shortcut for showing the app

---

js/views/attachment_view.js
js/views/message_view.js

Fixes #1260. Recent changes to attachment handling made it so we only listened for the `update` event after `render()`, but file views, having no async load to do, immediately trigger the `update` event during `render()`.
Also: noticed that we overwrite `this.view` (initially `FileView`, later a video or audio player), so gave the `FileView` its own member variable.

Fix: Show attachment views; they trigger update synchronously

---

stylesheets/_conversation.scss
stylesheets/_ios.scss
stylesheets/manifest.css

First, this fixes file attachment styles in iOS theme. They weren't fully updated when we moved to the gray conversation background color, resulting in little gray blobs instead of nice little chat bubble tails. Also, in the message detail screen, they didn't have nice styling - removed some too-specific CSS rules.
Second, this makes the background color of the message detail screen gray, so that you can see outgoing messages in Android theme, incoming messages in iOS theme. White on white was too hard to see.

File attachment styles, gray background for message detail screen

---

js/background.js
js/debugLog.js
js/views/recorder_view.js

Fixes #1266.
First, we remove recorder UI when we fail to 'getUserMedia'.
Second, we print `error.stack` instead of just `error` for `console.log()` which will give us more data.

Failed audio note

---

js/libtextsecure.js
libtextsecure/outgoing_message.js

Pending verification that ios and android can handle DataMessage protos wrapped in Content protos, we should stop sending legacy (nonwrapped) DataMessage protos. Eventually we'll be able to remove support for receiving them.

Stop sending legacy DataMessages

---

stylesheets/android-dark.scss
stylesheets/manifest.css

* Debian 9, Chrome 59.0.3071.109 64-bit
Fixes the "choose file" and "capture audio" button colors to match the rest of the Android dark theme.

Fix dark theme button hover color

---

components/emojijs/demo/emoji.css
stylesheets/manifest.css

Fixes #1265
Small CSS change to keep the left-nav item size consistent.

Make Jumbomoji normal size when in the conversation preview

---

js/models/conversations.js
js/models/messages.js
js/views/conversation_view.js

This is a relatively simple change - we now give key change and verification change notifications an `unread = 1` property when we save them.
It does have an interesting downstream effect: a conversation's unread count doesn't always reflect what is in the database, since we don't increment `unreadCount` when adding one of these notifications. A couple code changes were required to allow for this.
The trickiest case was this scenario, which we handle properly:
- Alice gets a direct message from Bob, pushing the badge number to 1 on desktop
- Alice was exploring the verify safety number feature with Bob in a group, and went back and forth a couple times. Three notifications show up in the group on desktop.
- On her phone, Alice navigates to the conversation with Bob, and sees four things …

Show last seen indicator for key change and verification notifications

---

js/libtextsecure.js
libtextsecure/outgoing_message.js

A bit of cleanup on the heels of e8548879db405d9bcd78b82a456ad8d655592c0f.
* Simplify some code
* Remove an unused property
While I was there I also noticed we were creating a new padded plaintext buffer for each recipient, which is unnecessary since the plaintext message is the same for everybody.

Legacy message cleanup

---

stylesheets/_android.scss
stylesheets/_conversation.scss
stylesheets/_ios.scss
stylesheets/android-dark.scss
stylesheets/manifest.css

Fixes #1291.
The :before technique for adding the icon was removed, because it resulted in some rendering issues when the layout pressure in the message bubble got too high - you would see a partial icon. This solution shrinks the icon a bit when the filename wants to expand to take its space.
The iOS bubble width also needed special care to ensure it didn't expand to accommodate the very wide filenames. Beyond that, overflow: hidden needed to be applied at several levels to make everything behave as expected.

Truncate long filenames in attachments

---

.jshintrc
_locales/en/messages.json
background.html
js/background.js
js/libtextsecure.js
js/models/conversations.js
js/models/messages.js
js/signal_protocol_store.js
js/views/conversation_view.js
js/views/identity_key_send_error_view.js
js/views/key_verification_view.js
js/views/message_detail_view.js
js/views/message_view.js
libtextsecure/message_receiver.js
stylesheets/_conversation.scss
stylesheets/manifest.css
test/index.html
test/keychange_listener_test.js
test/storage_test.js

Verification notifications:
- We were showing identity key notifications too often (when we didn't have an identity key before, for example)
- We were showing verification notifications too often (when we got them from contact syncs)
- Because contact sync can send us `UNVERIFIED` keys, a number of changes were needed in the `Conversation` model, our `onVerified` handler, and in `processVerifiedMessage`.
A number of UI updates to match Android: 
- More informative strings which talk about verifying a safety number, and not the contact themselves
- A notification that a group message did not reach all recipients
- When outgoing identity key errors happen (because a getProfile didn't happen beforehand) we have a nicer experience on the message detail screen. A View button like Android, …

UI modifications to match Android, handle UNVERIFIED syncs, and more!

---

_locales/en/messages.json
background.html
js/views/confirmation_dialog_view.js
js/views/key_verification_view.js
test/index.html

It's a bit of an edge case, but we previously got the scenario very wrong.
Because we send a null message to the target of our verify/unverify, we can discover a safety number change right after a verify/unverify decision is made. Before this change the button would flip back to 'not verified' if the user attempted to verify. This would likely cause users to immediately click it again to ensure that their decision was made.
This change introduces a popup dialog telling the user what happened. It also catches this situation and re-renders the view with the new safety number.

Show warning when we discover key change on verify

---

_locales/en/messages.json
background.html
js/views/confirmation_dialog_view.js
js/views/message_detail_view.js
stylesheets/_conversation.scss
stylesheets/manifest.css

A big red 'Delete these message' button at the bottom of the message detail pane, with a confirmation dialog to be sure.
I did notice a bit of weirdness with the confirmation dialogs we have right now - when one is active, you can tab around to all focus-able controls and interact with them normally. You can send messages with the dialog showing. Not ideal, but not blocking.

Delete individual message

---

js/views/conversation_view.js

We don't want to throttle other calls to `getProfiles()`, so we localize this change to the fetch we do when we first open a conversation.

Throttle profile gets when a conversation is opened

---

js/models/conversations.js
js/models/messages.js

Bullet-proofs `_setVerified` and `handleDataMessage` against rejections and the weird behavior we get from `$.Deferred`.
`handleDataMessage` is especially important to get right, because anything that causes us to fail to call `resolve()` will wedge the conversation. Nothing can go out or come in for that conversation until the app is restarted.

Bullet-proof _setVerified and handleDataMessage against rejections

---

js/models/conversations.js
js/models/messages.js
js/views/conversation_view.js

Got a bug report that the badge, with an unread count, persisted despite switching back and forth between other conversations.
This change makes a number of small tweaks to ensure that our `inProgressFetch` promise in `ConversationView` is resolved, so `markRead()` can be called in `onOpened().`

Bulletproofing: inProgressFetch promise flow

---

app/locale.js
main.js

I noticed that on Linux we were always falling back to the 'en' locale because the local we got from `app.getLocale()` seemed to be a blank string. Not sure if this will fix the Linux situation, but I know for sure that it is required for Windows:
> **Note:** On Windows you have to call it after the `ready` events gets emitted.
(via: https://github.com/electron/electron/blob/master/docs/api/app.md#appgetlocale)
Update: This has been verified as fixing the problem on Linux.

Electron: Load locale only after 'ready' event

---

Gruntfile.js
background.html
js/background.js
js/database.js
js/debugLog.js
js/delivery_receipts.js
js/libtextsecure.js
js/models/conversations.js
js/models/messages.js
js/read_receipts.js
js/reliable_trigger.js
js/signal_protocol_store.js
js/views/conversation_view.js
libtextsecure/account_manager.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js
libtextsecure/storage/groups.js
libtextsecure/storage/unprocessed.js
libtextsecure/task_with_timeout.js
libtextsecure/test/index.html
libtextsecure/test/task_with_timeout_test.js
test/index.html
test/reliable_trigger_test.js
test/storage_test.js

When a message is first received, we cache it. After we've decrypted it, we update that cached copy of the message. The message is only removed from our cache when the application confirms that it is done processing it. On startup we load all messages from the cache and attempt to process them once more. We'll try five times before giving up.
Additionally, for messages visible to the user, we check for duplicates before letting the application process any incoming message.
Architecture:
- Two new migrations. The first is for `unprocessed` messages, with one currently-unused index by `timestamp` (when the message was received). The second is to add a `unique` index to the `messages` data store on three fields `[source, sourceDevice, sent_at]`
- All events (except `error`) emitted by …

Caching, retry and de-duplication of incoming messages

---

app/auto_update.js
aptly.sh

Today our automatic upgrade logic checks every hour to see if there is a new upgrade available. If there is, we pop a dialog for the user to decide whether to upgrade later or right now.
Previously we were popping that dialog once an hour, no matter whether the user had made a decision or not. This ensures that we never show more than one dialog.

Fix: Too many automatic upgrade dialogs

---

js/background.js
js/conversation_controller.js
js/debugLog.js
js/keychange_listener.js
js/models/conversations.js
js/reliable_trigger.js

Discovered a class of issues around conversation handling - either saving over what's in the database, or relying on what's in memory instead of going to database to be sure. Now we always pull from the database first.
Primarily affects these scenarios:
- Contact sync
- Verification sync
- Group sync
One other small change: applying our overridden `Backbone` trigger to `Collection` as well.

Fetch conversations first!

---

js/background.js
js/libtextsecure.js
js/read_receipts.js
libtextsecure/message_receiver.js

With the new caching of unprocessed envelopes, I've noticed that read receipts are pretty frequently left in the cache because the target message wasn't found. 
This adds some logging to help track down the underlying problem.

Read receipts: Log sender and timestamp when related msg not found

---

js/signal_protocol_store.js
test/storage_test.js

Because users will see this upon first trying to communicate with a new contact if they're quick about it.

isUntrusted: Return false if firstUse is true

---

js/background.js
js/conversation_controller.js
js/views/conversation_search_view.js

Anyway, `findOrCreateById` with no `type` specified didn't succeed, because the conversation didn't validate. Discovered this problem handling sync'd group details when setting up a new desktop instance today.

ConversationController.findOrCreateById instead of private-specific method

---

app/auto_update.js
main.js

[A recent update](https://github.com/WhisperSystems/Signal-Desktop/pull/1319) changed how we load locale messages - we had to do it after the app's 'ready' event. That change didn't update how the auto-update dialog loaded locale messages. This PR fixes that.

Fix auto-update pop dialog: provide localized messages

---

app/menu.js
background.html
js/background.js
js/views/app_view.js
js/views/inbox_view.js
main.js
preload.js

Electron users can now access the debug log UI from the menu bar (View -> Debug Log), making it possible to submit logs even if you haven't finished registration, or if you are registered but the inbox view just hasn't appeared yet.
This required extracting the management of a DebugLogView out of InboxView, and moving it up a level (in the view/DOM hierarchy) to AppView.

Move debug log to the View menu

---

_locales/en/messages.json
background.html
index.html
js/background.js
js/libtextsecure.js
js/models/conversations.js
js/models/messages.js
js/views/conversation_view.js
js/views/inbox_view.js
libtextsecure/event_target.js
libtextsecure/message_receiver.js
stylesheets/_conversation.scss
stylesheets/_global.scss
stylesheets/android-dark.scss
stylesheets/manifest.css
test/fixtures_test.js
test/index.html

A number of changes needed to be made so that `MessageReceiver` could know when its queue was truly processed:
- `dispatchEvent()` now surfaces the return values of all listeners back as an array of results
- `MessageReceiver` now has an `incoming` property, an array of all promises which encompass the initial decrypt, response to the server, caching, and finally queuing for all all in-flight envelopes. It allows us to ensure that when we get that 'empty' notification from the server, we can wait for all messages that came in right before that to be queued.
- when doing handling of an envelope in the primary queue, we wait until processing of that envelope is complete before moving onto the next one. This change has the biggest potential for larger effects on application behavior, but …

Animated loading screens on startup and first conversation load

---

js/models/messages.js

Our comparisons in `fetchConversations()` weren't doing things properly before. Even if our expected `unreadCount` was `1`, we would always do two fetches. Yes, we should add an index and do this right. But for now, this will save us a fetch.

Don't do second fetchConversation call if we have all unread

---

js/conversation_controller.js
js/models/messages.js
js/views/attachment_view.js
js/views/conversation_view.js
js/views/message_view.js

Today the application keeps all previously-viewed conversations and messages (including attachments) in memory until restart. This can add up to a whole lot of memory usage, especially in high-traffic conversations with lots of large media.
This change sets up a timer in `ConversationController` to tell all conversations to prune themselves every half-hour. When a `ConversationView` finds that its conversation has emitted this `prune` event, it will do one of two things:
1. If it's been over an hour since the conversation has been opened or scrolled, and it's not currently showing, we'll unload it completely. We'll need to load it up once more, from scratch, when the user requests it.
2. If the conversation doesn't meet those criteria, but we're scrolled to the bottom (showing the most …

Unload conversations and old messages every half-hour

---

js/views/app_view.js

If the 'empty' event is fired between the `updateInbox()` call and the new `InboxView()` call afterwards, then the loading screen will never go away. We fix that by immediately creating the `InboxView` but only adding it to the DOM when the backing data is ready.

AppView.createInbox() - set this.inboxView immediately to be ready

---

libtextsecure/message_receiver.js

I notice some unpredictability with 30+ cached - sometimes the loading screen would wait until they were all dealt with before starting up, sometimes the loading screen would disappear quickly.
This makes it predictable. When `MessageReceiver` starts up, the very first thing added to the queue are the messages we weren't able to successfully process.

MessageReceiver: Ensure that we queue all cached first

---

js/models/conversations.js
js/models/messages.js

I was thinking about how we might get duplicate read receipts sent by one client, and then I realized that we do queue `markRead()` calls, but we don't wait for all of their database writes to complete before returning. 
So it's definitely possible for two `markRead()` calls, right in a row (say from a click and also from the lazy scroll), to send read receipts for the same message. The first `getUnread()` call returns the full set, and the second returns some subset of the first because the database writes are incomplete.
Now it's one atomic action.

Conversation.markRead() - wait for all database saves

---

js/views/conversation_view.js

`unload()` is a more comprehensive method for doing what the close handler was trying to do before. We were missing just one thing in `unload()`, however - stopping the autosize management for the message composition text box.

ConversationView: when windows are closed, call unload()

---

js/rotate_signed_prekey_listener.js
js/wall_clock_listener.js

I left Electron running overnight last night, and my log was completely filled with two log entries: 'time travel detected!' and 'Next signed key rotation...'
This PR solves that by:
1. Removing the `console.log()` call when we detect time travel
2. ~~Reducing how often we check for time travel - every 5 seconds instead of every second~~
3. ~~Only calling `setTImeout()` to schedule the signed key rotation if the scheduled time has changed, or if we haven't scheduled a timer yet.~~

Minimize time travel logging

---

js/background.js
js/delivery_receipts.js
js/expiring_messages.js
js/libtextsecure.js
js/models/conversations.js
js/models/messages.js
js/read_receipts.js
libtextsecure/message_receiver.js

Three main changes:
- Delivery and read receipts are now handled in such a way that the overall `MessageReceiver` queue knows how to wait until they are resolved. This means that as we catch up, processing a large number of messages on startup, we'll also be done processing their read receipts by the time the loading screen goes away. This means we won't have ongoing changes to conversation unread counts once the inbox is shown. This also prevents a race condition with disappearing messages, where the message is deleted, but we load and display the conversation before all the deletes propagate, so we show a message that doesn't exist in the database (it went away on restart, but it's the kind of thing that reduces confidence in disappearing messages).
- Promises from …

A couple synchronization/logging fixes: disappearing messages, read/delivery receipts

---

js/libtextsecure.js
libtextsecure/libsignal-protocol.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js

~_Note: Dependent on the work in this PR: https://github.com/WhisperSystems/libsignal-protocol-javascript/pull/29. Need to merge that PR and pull `dist/libsignal-protocol.js` from that project into this PR._~
This PR uses the new ability to set the `messageKeysLimit` on `SessionCipher` to remove the limit when communicating with your own devices. We only do this for `SessionCipher` objects which are used for encryption/decryption - there are a number of other instantiations which are used entirely to do session management.
A number of open issues reference this error "Too many message keys for chain": https://github.com/WhisperSystems/Signal-Desktop/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22Too%20many%20message%20keys%20for%20chain%22
Hopefully these changes will fix that issue. …

Set messageKeysLimit to unlimited if communicating with our devices

---

js/libtextsecure.js
js/views/key_verification_view.js
js/views/message_detail_view.js
js/views/message_view.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js
stylesheets/android-dark.scss
stylesheets/manifest.css

Went through the new features ready for release to the Chrome Web Store today, and made a number of small fixes:
- _Key verification error popup: Remove cancel, empty resolve()_ - this shows if we find that a contact's verification number has changed when we try to verify the old number. It didn't need anything but an 'ok' button.
- _Make the application loading screen dark in the dark theme_ - It flashes from white to dark gray on startup because the base index.html doesn't know about theming, but after that it's on-theme.
- _Fix 'retry message' scenario: they are now content messages_ - It seems that because of some of the legacy-related changes [like this commit](https://github.com/WhisperSystems/Signal-Desktop/commit/3afe3780638a776e68511acc1510c25d7df27bc9), we need to use a Content …

A number of small fixes

---

_locales/en/messages.json
js/expiring_messages.js
js/libtextsecure.js
libtextsecure/message_receiver.js

Discovered yesterday a potential reason for high resource usage on startup: many duplicate calls to functions dealing with expired messages, leading to many concurrent DB requests for expiring messages, and therefore many duplicate deletions for the same message. So we `_.throttle()` these functions to once per second.
Also realized that the recent work to handle read receipts and delivery receipts within the overall incoming message queue (while loading screen is showing) wasn't quite working. Turns out that we weren't flowing promises back through `handleSyncMessage()` in `MessageReceiver`.
Finally, a quick change to make it easier to localize a confusing string.

Disappearing messages: Performance and synchronization

---

js/background.js

This causes hangs in the incoming processing queue whenever we run into an error on decryption. Bad news!

Give initIncomingMessage envelope in background.js error handling

---

js/models/conversations.js
js/views/conversation_view.js

The `Conversation` model's `isVerified` and `isUntrusted` both went to the protocol layer, but were not prepared for rejected promises resulting from missing records. This prevented send in large groups where there has never been a message exchanged with one of the members.
Originally reported here: https://github.com/WhisperSystems/Signal-Desktop/issues/1349#issuecomment-321497611

Handle rejections from protocol layer (due to missing records)

---

js/expiring_messages.js

Discovered a [user log where expiring message checks were happening constantly](https://gist.github.com/cd7bf6292b6368b3da0c52309fadeddf). This ensures that a very large timeout doesn't roll over into immediate callbacks.

Add a max setTimout for expiring messages (over max == immediate)

---

appveyor.yml

Discovered another symlink causing problems on windows, this time all of our emoji images. When we build the ASAR on windows, those files weren't getting included. This change takes advantage of the fact that the appveyor build steps are unique to windows, and copies all of the emoji images from `components` to `images`.

Copy emoji from components to images directory for asar creation

---

js/views/conversation_view.js

Because we do a number of async checks before allowing the real send to begin, on a slow machine or when doing a lot of work (like receiving a lot of messages) there can be a noticeable delay between hitting Enter and the clearing of the text in the message box. In fact, newly-typed text can be added to the previous message if the delay is long enough.
This prevents any interaction with the message box until the send has either been prevented or has started.

Disable message box between send request and final send begin

---

js/background.js
js/libtextsecure.js
js/models/conversations.js
js/views/conversation_view.js
libtextsecure/errors.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js

I discovered an issue that Signal Desktop users who had enabled the 'Require approval for safety number changes' option may run into after they've installed `0.42.1`. Here's the scenario:
- Alice, on `0.41.x`, has a conversation with Bob
- Bob reinstalls and sends some messages
- Alice sees some "Safety number changed" errors from Bob because of the safety number change
- Alice upgrades to `0.42.1`, released this week, which always shows incoming messages even with safety number changes
- Bob sends another message
- Alice sees it is immediately decrypted
- Unfortunately, at this point Bob's old messages are still showing as "Error handling incoming message", and there's no way to recover them.
This is because there was no code put in place to 'bring forward' these old messages when we …

Decrypt any IncomingIdentityKeyError still sticking around

---

js/models/messages.js
libtextsecure/message_receiver.js

It turns out setting our `received_at` date immediately after receiving from the websocket is causing problems for situations when the application downloads a lot of content at once. So, we both remove that set of `received_at` and improve our sorting, so we sort by `received_at`, then `sent_at`.

Set receivedAt to post-encrypt time, not actual received time

---

js/views/conversation_view.js

We were being too aggressive on unload of a conversation, removing something from memory which was a property of the long-lived `Conversation` model. What we need to get rid of is anything associated with _viewing_ that model.
Fixes #1370

Don't revoke convo avatar URL on unload - we will need it again

---

.travis.yml

This turns off TravisCI email notifications. Github does a fine job telling us about the things we care about, otherwise we can always go there and see the results.

Travis doesn't respect the repo/organization email so turning off

---

js/models/conversations.js
js/views/conversation_view.js

Logging changes for four scenarios:
- How long it takes to get a message through the pre-send checks
- How long it takes to open a conversation for the first time
- The timestamp of any message we send to correlate with logs from other devices
- Add conversation ID to 'decrypt old identity key errors' start/end
Note, there's one more interesting metric that we'll be able to capture with these changes - the space in the log between the 'pre-send checks' log entry and the 'message timestamp' entry. That will tell us how long we are hanging out in the Conversation's queue before moving forward with the message send.
Lastly, we now re-enable the message composition text box if the user presses enter with no text provided. Previously the message would stay disabled until the user clicked with …

More logging, small message composition bug-fix

---

js/spell_check.js
package.json
preload.js
yarn.lock

These changes enable a number of scenarios:
- Context menu behavior with multiple spelling errors - previously the context menu would show only the last error in the target text.
- Non-`en-US` support on Linux. You can use `apt-get install hunspell-en-ca` (for example) to install additional hunspell dictionaries (we check `/usr/share/hunspell` for anything other than `en-US`). As long as the `os-locale` module is able to detect that you want the `en-ca` locale, it should just work.
- The `HUNSPELL_DICTIONARIES` environment variable can be set on Linux to override our default search location.
Note: 
- The story for Windows 7 and earlier is worse than Linux. You get the `en-US` dictionary by default, but you'll need to do two things to enable other locales: 1) download the appropriate …

Spell check: support for multiple errors, languages, and platforms

---

app/locale.js
js/spell_check.js
package.json
yarn.lock

I ran Electron in Spanish to test out spell check, and discovered that a bunch of UI was missing strings. A key feature of i18n in Chrome Apps that we hadn't yet reimplemented.
This is a simpler change than https://github.com/WhisperSystems/Signal-Desktop/pull/1379, so it's probably the better solution.

i18n: Failover to english when language is missing a string

---

js/libtextsecure.js
libtextsecure/sendmessage.js
libtextsecure/sync_request.js

Based on [this bug](https://github.com/WhisperSystems/Signal-Desktop/issues/1208#issuecomment-323129181), it seems like we're running into errors sending the message to kick off the sync, so positive logging as well as error logging is included.

Add logging to help track down problems with Sync

---

js/delivery_receipts.js

I've noticed that delivery receipts often hang out in my queue, retried on every restart. Where are they coming from? Why are they hanging around? This logging will help us track down the underlying issue.

Additional logging when we get delivery receipt for unknown message

---

js/libtextsecure.js
libtextsecure/message_receiver.js

I noticed, looking through the logs [submitted here](https://github.com/WhisperSystems/Signal-Desktop/issues/1364), that a common log entry right before a long delay is `addToCache`. Here's a delay of almost nine seconds:
```
2017-08-21T17:26:35.671Z addToCache +[REDACTED]109.1 1503336393444
2017-08-21T17:26:44.135Z queueing envelope +[REDACTED]109.1 1503336393444
```
And what does `addToCache` do? It converts an `ArrayBuffer` to a `string` so that the `envelope` can be stored in the cache. But because IndexedDB supports `ArrayBuffer` natively, this is unnecessary anyway.
This might just speed things up a bit!

MessageReceiver cache: Don't convert to string for save

---

js/background.js
js/libtextsecure.js
libtextsecure/message_receiver.js

There's really no reason to retry encryption errors again if they've already been made user-visible in a conversation. It's confusing for users anyway, since new errors pop up when there has been no incoming message to cause it: https://github.com/WhisperSystems/Signal-Desktop/issues/1376

Remove errors from the cache when they are shown to the user

---

_locales/en/messages.json
background.html
js/background.js
js/backup.js
js/libtextsecure.js
js/views/inbox_view.js
js/views/migration_view.js
js/views/whisper_view.js
libtextsecure/message_receiver.js
manifest.json
stylesheets/_global.scss
stylesheets/manifest.css
test/index.html

To support testing, this is all behind a flag for now. To enable it, open up the dev tools to the background window and enter this:
```javascript
window.storage.put('migrationEnabled', true);
window.location.reload();
```
Once you've gone through the export process, the application will be disabled to prevent conflicts between two duplicate devices. If you haven't really migrated to a new install, you can reset your export status like this:
```javascript
window.storage.put('migrationState', 0);
window.storage.put('migrationEverCompleted', false);
window.location.reload();
```
The flow goes like this:
1. Banner at the top telling the user that the build is expired, they should move to the new Signal Desktop. 'Migrate' button which shows a confirmation dialog.
2.  A page that looks like the …

Full export, migration banner, and full migration workflow

---

js/backup.js
js/views/inbox_view.js

This user reported a failing export: https://github.com/WhisperSystems/Signal-Desktop/issues/1398
Ultimately we discovered that it was due to an extremely long group name. So now we limit group and contact names to 30 characters when we go to the filesystem.
But in the process we realized that the group id is not something we wanted in clear-text. So, as with phone numbers, we only log the last three characters of the group id.

Chrome export fixes: too-long names, redact group ids

---

js/storage.js
js/views/import_view.js

This morning we received a report that Electron import seemed to finish successfully, but restart of the app resulted in a 'import was incomplete' screen: https://github.com/WhisperSystems/Signal-Desktop/issues/1399
This tries to solve that by waiting for all six final database writes before declaring that the import is complete. My theory here is that all the database activity causes `console.log()` statements (which go to the database) to fall behind, which creates a backlog with these six final writes at the end.
And that user, in two different attempts, clicked Restart fast enough that the backlog hadn't been processed.

Import: Wait until all db writes resolve before saying we're done

---

js/background.js
js/conversation_controller.js

We're getting reports of contacts (or at least contact metadata updates) [not showing up in Desktop](https://github.com/WhisperSystems/Signal-Desktop/issues/1324) like they are in mobile apps, so this introduces some error handling to be sure that any problems saving an incoming contact are logged.

Additional contact error handling

---

js/libtextsecure.js
libtextsecure/message_receiver.js

Previously we were crashing whenever we got a sync message with blocked messages.

Fix handling of sync message with blocked numbers

---

js/backup.js

We start with `active_at` to ensure that the directories are sorted like they are in the UI.
Next we show the human-readable value - the `name` of the group, the `name` of the contact.
Because contacts and groups can have the same names, and may have even been active at the same moment, we add one more datapoint to disambiguate the directories on disk: the `id`.
Note: group ids are binary and have a lot of weird characters. These are mostly turned to underscores via `sanitizeFileName()`, but they'll still be useful for disambiguation.

Export: Better disambiguate conversation directory names

---

js/libtextsecure.js
libtextsecure/task_with_timeout.js
libtextsecure/test/task_with_timeout_test.js

Some log analysis today uncovered a bug in `createTaskWithTImeout` - it was claiming that a task hadn't completed in time when that task threw.
With this fix, we now catch anything thrown by the task, call `clearTimer()`, then re-throw.

createTaskWithTimeout: Don't log expiration if task threw

---

stylesheets/android-dark.scss
stylesheets/manifest.css

Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1407.
Before:
After:

Export/Dark Theme: Increase banner text contrast for legibility

---

js/libtextsecure.js
libtextsecure/message_receiver.js

This is one of the types of messages that always hangs around until our retry limit is reached. But there's no reason for that. If we don't recognize this kind of message, we remove it from the cache.

Remove unknown group messages from cache - no need to retry!

---

js/backup.js

We had a user report of a crash on `conversation.name.slice()` - because the group in question had no name! Now we handle this situation, simplifying our code in the process.

Export: Properly generate directory names for nameless groups

---

js/background.js
js/libtextsecure.js
libtextsecure/message_receiver.js

When processing a contact sync with embedded identity key verification info, we
were running overlapping async fetch/save operations on the same conversation
model, causing a race that tends to clobber updates to the contact info.
In this change we extend the application-level contact info handler to block on
a subsequent call to the verification handler, which effectively serializes the
fetch/save calls, and relieves the need for the message receiver to trigger a
seperate event concerning the verification info on contact sync messages.
Fixes #1408

Fix race handling contact sync with verified info

---

js/background.js
js/conversation_controller.js
js/keychange_listener.js
js/models/conversations.js
js/models/messages.js
js/notifications.js
js/views/conversation_search_view.js
js/views/inbox_view.js
test/keychange_listener_test.js
test/views/message_view_test.js

Race conditions around re-fetching have caused some problems recently, so this removes the need to re-fetch conversations. They are fetched once or saved initially, and that is it. All interaction goes through the `ConversationController`, which is the central source of truth.
We now have two rules for Conversations:
1. If a conversation is in the `ConversationController` it doesn't need to be fetched, but its initial fetch/save might be in progress. You can wait for that fetch/save with `conversation.initialPromise`.
2. If a conversation is not already in the `ConversationController`, it's not yet in the database. It needs to be added to the `ConversationController` and saved to the database.
Note: These invariants will only hold once `ConversationController.updateInbox()` has resolved, …

Fetch conversations once, clean up ConversationController API

---

js/background.js
js/conversation_controller.js
js/expiring_messages.js
js/models/messages.js
test/fixtures_test.js
test/models/messages_test.js

A recent change to fetch conversations less didn't take into account all that can happen in the app without the inbox loaded. Inbox load happens when the window is shown, but messages can come in with the app in the background. In that case, the conversation wouldn't have been loaded from the database, but would be saved to the database with partial data anyway, losing data.
This change fetches all conversations as soon as the the data store is ready for a fetch. It also introduces failsafe throws to ensure that synchronous `ConversationController` accesses don't happen until the initial fetch is complete. A new `getUnsafe()` method was required to account for some of the model setup that happens _during_ that initial conversation fetch.
Fixes #1428

Fetch all conversations on startup of app, not on inbox load

---

js/views/message_view.js

When we relied on the actual value of the color property to be supplied to the `updateColor()` change event listener, sometimes it would be `null`. Then the conversation bubbles would have no color at all, making the text hard to read.
This happens for iOS users who have been communicating with a phone number, then add a contact for that user. (Because iOS does not supply a color in its contact sync data)

MessageView: Handle change of color to null, call getColor()

---

js/backup.js
test/backup_test.js
test/index.html
test/views/message_view_test.js

Three changes:
1. Limit attachment names to 30 chars
2. Reintroduce last contact date in conversation dir name
3. Add tests for most `backup.js` helper functions
This should make it more likely that we'll succeed on Windows, which has a path length limit.
Bonus: Fix `MessageView` tests, which were failing during code coverage runs
_Note: This is an export format breaking change, since it changes how attachment filenames are generated. Any attachment filename longer than 30 characters will cause a failure on import if using an older build that doesn't trim filenames._

Export: Limit path lengths of attachments, add tests

---

js/background.js
main.js

We got a report that, when unlinked, Electron shows the loading screen forever. This is because we don't get the 'unauthorized' event, because we never even try to connect to the websocket. This change attempts to connect to the websocket if `Registration.everDone()`, instead of just `.isDone()`.
Also, we got a report of this, an error dialog on startup, now fixed:

Fix loading screen hang when unlinked, fix error dialog on startup

---

js/views/message_list_view.js

I believe this is typo.
I peaked at the profiler and found this:
This change doesn't actually seem to improve the situation much. It mostly just shuffles time spent from `scrollToBottomIfNeeded` ->`measureScrollPosition`.
Throttling `measureScrollPosition` does effectively solve this particular hotspot, but I'm not sure it guarantees proper behavior - e.g. with respect to the scroll indicator. Maybe those more in the know have an idea for a next step?

scroll only when needed

---

stylesheets/_conversation.scss
stylesheets/_variables.scss
stylesheets/manifest.css

Max-width on a message bubble should be about 30em for the good readability.
However, when the window isn't wide enough, bubbles must be further limited.
The transition should happen around the point that these two rules intersect,
but it was kicking in a little late, which caused the bubbles to jump from wider
to shorter as you widened the window past a certain point. This change adjusts
the threshold for smoother and more consistent bubble resizing.
The variable name $big-avatar-min-width is an artifact of a past design and was
previously used in multiple places, but it no longer makes sense in this context
so it has been discarded.
Fixes #1446

Fix bouncy bubble widths

---

stylesheets/_conversation.scss
stylesheets/_index.scss
stylesheets/manifest.css

This removes some errant horizontal scrollability from the conversation list and the message list.
Fixes #1436

Fix horizontal scrolling in convo/message lists

---

js/views/message_list_view.js

It turns out that this pull request did actually break expected behavior: https://github.com/WhisperSystems/Signal-Desktop/pull/1441
When you send a message, for example, it doesn't look like it sent because we don't scroll the window down. With this small change, we scroll down once more.
It's true, though, the code is very uninituitive. The name of the method is 'IfNeeded' and then inside the method we say that we should scroll to bottom if we're at the bottom already. So, I added a comment to try to make this easier to understand as you read it.

Scroll to bottom when adding a new message (on send, receive, etc.)

---

js/models/conversations.js

Though it is possible to verify yourself in Android and iOS, it's confusing to users and it really doesn't mean anything anyway.
Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1451

	Don't show notifications for verified state change with yourself

---

main.js

When clicking on a notification in Windows when a window had been stuck to one side of the screen using Snap, the window would be repositioned. We now use a less-aggressive technique for calling attention to ourselves.
Fixes #1429 (thanks for the correction, Lilia)

focus() visible window on show-window instead of show()

---

js/debugLog.js
js/libtextsecure.js
js/models/messages.js
libtextsecure/message_receiver.js

On a recent trip through a CPU profile taken while Signal Desktop churned through a large backlog of messages (inspired by #1457), it was clear that console.log was a major source of time spent, primarily the sort operation required after every new entry is added to the Backbone collection. So, three different techniques to combat this:
1. Reduce the maximum number of entries in the collection from 5k to 2k
2. No more logging of add/update/remove queue in MessageReceiver
3. No more log entries in Message.handleDataMessage main codepath

Log entry max to 2k, remove logging in hot codepaths

---

js/libtextsecure.js
libtextsecure/websocket-resources.js

Users have been running into difficulties with spurious socket disconnects, even with the application in focus. And there seem to be mysterious ~90-second gaps in the log before each of these socket timeout messages: https://github.com/WhisperSystems/Signal-Desktop/issues/1075
This additional logging will help us determine when we sent the original keepalive message, what kind of delays we're seeing between the two. It should only be a one second of delay, but I'm guessing that it is being extended out to ~90 seconds.

Additional logging to help track down socket disconnect problems

---

js/libtextsecure.js
libtextsecure/message_receiver.js

Resolve extremely long loading screen time when dealing with repeated redeliveries and socket timeouts, as seen in #1426.

Trigger empty event on keepalive timeout

---

js/libtextsecure.js
libtextsecure/ProvisioningCipher.js
libtextsecure/account_manager.js

Fixes exception seen in https://github.com/WhisperSystems/Signal-Desktop/issues/1465#issuecomment-329074141

Fix exception in provisioning cipher

---

_locales/en/messages.json
background.html
js/views/migration_view.js

Because export might take a couple minutes, we now set expectations that it might take 'several minutes' instead of just 'please wait.'
We also promote 'Install new Signal Desktop' from a text link in the instructions to a button. This is important on the 'Completed' screen because it is bigger and to the left of the 'Export Again' button, which previously drew primary focus on that screen.
Lastly, we also remove the title-specific element of the support link, so we're resilient to title changes in the future.

Export: Improve usability - timing expectations, install button

---

package.json
yarn.lock

We needed to update `electron-builder` to maintain pinned status on Windows taskbar when upgrading to a new version. Fixes #1463.
We tweaked Linux build config to fix two bugs:
- Our app was put into the 'Other' category, when it should be 'Internet.' Fixes #1460.
- Alt-Tab in GNOME didn't show an icon. Fixes #1432.
Also: updated a few other dependencies with minor updates: `config`, `grunt-exec`, and `spellchecker`

Update builder for Windows taskbar, tweak Linux config for GNOME taskbar

---

background.html
js/views/install_view.js
stylesheets/manifest.css
stylesheets/options.scss

Allow recovery from a failed http post during the provisioning flow, which would leave the user stuck on the 'generating keys' screen, as seen in https://github.com/WhisperSystems/Signal-Desktop/issues/1010#issuecomment-328102483.
Also log all provisioning errors.

Better install view error handling

---

js/views/app_view.js
js/views/inbox_view.js
stylesheets/_global.scss
stylesheets/_index.scss
stylesheets/manifest.css

This change applies theming one level higher in the DOM so it affects the debug log popup. It's now in the overall `body` tag instead of its first child `div`.

Move app theming from IndexView to AppView

---

appveyor.yml
build/grunt.js

This `grunt.cmd` corruption is a known issue that nobody has tracked down yet: https://github.com/gruntjs/grunt-cli/issues/113#issuecomment-329575861
Sadly, today it upgraded itself from intermittent to something really worth some effort. This is the simplest solution.

Bypass the frequently corrupt node_modules/.bin/grunt.cmd on windows

---

images/emoji/apple

A little bit of cleanup missed in the transition to npm-sourced emoji data.

Remove images/emoji directory

---

Gruntfile.js
fix_broken_perms.sh
package.json

No more `win-unpacked`/`linux-unpacked`, so we need to extract downloaded zips into their own folders manually.

Update our release scripts to match changes in electron-builder

---

CONTRIBUTING.md
README.md
package.json

The world has changed - Yarn, Electron, and build tools, oh my! Also, I think we can better order `CONTRIBUTING.md` to reflect how often various parts will be needed.
The best way to review this is to look at the resultant markdown. :0)

Documentation refresh for the world of electron

---

js/views/conversation_view.js

Just noticed some spurious "RangeError: Maximum call stack size exceeded" statements in the console. Investigation reveals they can be repro'd by selecting text in a message, and then dragging the text around.

Fix RangeError on non-file drag/drop events

---

js/libtextsecure.js
libtextsecure/message_receiver.js

Rather than throw an error, just log call messages and drop them. This way we distinguish them from incorrectly encoded content messages, and don't insert unnecessary red flags and stacktraces in debug logs, as seen in https://github.com/WhisperSystems/Signal-Desktop/issues/520#issuecomment-331697317

Log call messages

---

appveyor.yml
package.json

Woo! It's here!
`electron-builder` supports our extended validation code-signing cert, but only on windows. Our release process must now include a signing step on windows.
Also: Moving to signed windows builds will require that all of our windows users reinstall from scratch, because auto-update will very likely reject the new builds with a different signature.

Add certificate name for windows code-signing

---

js/background.js
js/libtextsecure.js
libtextsecure/message_receiver.js

Today we wait for a keepalive request to fail, but those only happen every 55 seconds. This change immediately forces a disconnect in the case that the browser tells us that we're offline.

Disconnect from socket faster on complete loss of network access

---

preload.js

We're still having problems with the Node.js websocket in Electron, tracked here: https://github.com/WhisperSystems/Signal-Desktop/issues/1075
This takes our workaround and amps it up. Instead of calling `setImmediate` after making a web request, we do it every second. I'm hoping that this extreme approach solves the problem, and then we can do the work to pare back as necessary.

Further workaround to try to push node.js event loop forward

---

js/background.js
js/libtextsecure.js
libtextsecure/message_receiver.js

Pretty simple, really. It's a little more involved than you might expect, since multiple `MessageReceiver` instances may be created over the lifetime of the process.

Only retry messages on startup, not every sockect reconnect

---

package.json
yarn.lock

Security issue details here: https://electron.atom.io/blog/2017/09/27/chromium-rce-vulnerability-fix

Update electron to v1.6.14 to get security fix

---

_locales/en/messages.json
_locales/fa/messages.json
_locales/no/messages.json
_locales/pt_BR/messages.json
_locales/pt_PT/messages.json
_locales/ro/messages.json
_locales/zh_CN/messages.json
_locales/zh_TW/messages.json

Also, remove unneeded (and potentially brittle) title from support link in English `importError` string.
As part of verifying these changes, I also did a review of all URLs in all language files to ensure that they still link to https://support.whispersystems.org.

Update strings for fa, no, pt_BR, pt_PT, ro, zh_CN, zh_TW

---

js/background.js
js/models/conversations.js
js/models/messages.js
js/notifications.js

Instead of adding OS notifications immediately when we find out about a new unread message, we wait until we get the 'empty' event from `MessageReceiver`. This tells us that our queue is empty.
This then prevents the parade of notifications if a machine wakes up from sleep. Basically covers situations that the loading screen doesn't already.

Only show notifications when done with sync

---

js/models/messages.js

Without this change, there's a race condition for the notification we show when we get the 'empty' event after a large backlog download. If four messages have come in, the last might not be included in the first notification. So the count shown would be three. And then, when the final message's `notify()` call does finish, another notification would be shown.

Ensure final message before 'empty' is ready for notification

---

js/logging.js

`log` was erroneously bound to `function log()` upfile, instead of `window.log`

window.onerror: move to proper window.log.error call

---

js/background.js

Somehow we ended up with two getSyncRequests. Let's delete this one and keep [the other](https://github.com/WhisperSystems/Signal-Desktop/pull/1530/files#diff-2650fb3e14b7f42d68a8766269c54434L145).

Remove duplicate definition of getSyncRequest

---

js/backup.js

Now that we log to disk, we no longer need the 'debug' object store from the Chrome export. Fixes #1531.

Remove 'debug' from the list of stores we import

---

main.js

We were inadvertantly disabling the fullscreen button due to a quick of the
BrowserWindow api. Add some guards to make sure we no longer save or use a
previously-stored `fullscreen: false` in our window configs.
Fixes #1516
See also: https://electron.atom.io/docs/all/#new-browserwindowoptions

Re-enable fullscreen on OSX

---

app/locale.js

I went to debug some failing tests locally and I got more/different failures because we were testing for english strings, but they were translated into Dutch because of my system locale setting.

Ensure locale is 'en' when NODE_ENV=test

---

app/logging.js
js/logging.js

Overriding `console.log()` in the main process should allow us to get an insight into auto-update behavior and other low-level things, all very useful for debugging.
Also, we now look for non-strings passed to `console.log()` and `JSON.stringify()` them first. No more `[Object object]` in our logs!

Override console.log in main process, handle non-strings

---

package.json

This will make electron-updater use the cdn-fronted updates.signal.org instead
of the s3 endpoint. You can verify it worked by looking at the url generated in
dist/latest-mac.json and dist/win-unpacked/resources/app-update.yml

Use cdn endpoint for auto update

---

package.json
yarn.lock

These changes ensure that the signing certificate of any binary pulled down as part of auto-update on Windows is in the trusted CA chain (not self-signed) and has the right `publisherName`. `electron-updater` also rejects any unsigned binary when asked to check the `publisherName`.
Note: the version chosen for `electron-updater` is the one released around the same time as the version of `electron-builder` we're using.
As an aside, a semantic release monorepo makes it really hard to track down when stuff was released. :0/

Update electron-updater and supply it with windows/publisherName

---

app/logging.js
js/logging.js
js/views/debug_log_view.js

An immediate response to the user request to see the log, and then we show the real data as soon as we've loaded it from disk.
Changes:
- the IPC exchange to get the log data is now async
- the API to fetch the log on the client side now returns a Promise
- in the main process, the only disk access done synchronoously is reading the contents of the log directory. The JSON parsing of the resultant log data is now split up into three chunks.
- We only send three keys from each log item to the renderer process: `msg`, `time`, `level`. Previously we sent the entire log entry with extra keys: `hostname`, `pid`, `name`.

Load debug log dialog immediately, then populate log data

---

background.html
js/background.js
js/delivery_receipts.js
js/libtextsecure.js
js/models/conversations.js
js/models/messages.js
js/read_receipts.js
js/read_syncs.js
js/views/contact_list_view.js
js/views/conversation_view.js
js/views/message_detail_view.js
js/views/message_view.js
libtextsecure/ProvisioningCipher.js
libtextsecure/account_manager.js
libtextsecure/api.js
libtextsecure/message_receiver.js
libtextsecure/outgoing_message.js
libtextsecure/sendmessage.js
protos/DeviceMessages.proto
protos/IncomingPushMessageSignal.proto
stylesheets/_conversation.scss
stylesheets/_global.scss
stylesheets/android-dark.scss
stylesheets/manifest.css

First pass at send/receive receipt messages...
Note some internal terminology have been changed. The messages/models formerly known as "read receipts" are now called "read syncs". These messages are exchanged only between linked devices and indicate that an incoming message was read on a linked master or sibling device.
The term "read receipts" now refers to ReceiptMessages of type READ. These messages are received from other Signal users and indicate that an outgoing message was read by that user.
ReceiptMessages can alternately be of type DELIVERY for encrypted delivery receipts. The delivery receipt event has been renamed and refactored slightly to handle them.
~TODO: Global opt-in/opt-out setting (or sync this from the phone?)~

Receipt messages

---

stylesheets/_conversation.scss
stylesheets/android-dark.scss
stylesheets/manifest.css

The new `.status` CSS rules for the checkmarks caused onboarding text to go vertical, because it was only 18px by 18px.

Make .status CSS rules more specific to fix onboarding text

---

js/views/file_input_view.js

This may just be the last image path problem left over from the move to Electron! :0)

Show proper icon when attachment is not an image

---

js/views/file_input_view.js

Previously we only had limits for audio, video, and image files.
Fixes #1553

Add 100MB file size limit for arbitrary file types

---

js/conversation_controller.js
js/views/conversation_list_view.js
js/views/inbox_view.js

We were inserting based on neighbor items from the DOM, instead of finding neighbor items from the collection, then finding those in the DOM.
Fixes #1500. Pretty sure. :0)

Fix intermittent conversation sort order problem

---

js/conversation_controller.js
test/fixtures.js
test/fixtures_test.js
test/index.html

For a while now, the three `InboxView` views at the bottom of the test page have been empty. This restores contents.
It also updates the fixtures shown in those views, making them suitable for taking screenshots:
- Bigger time differences between the messages in the group conversation, since the default granularity is minutes
- A most recent message for every conversation to ensure proper sort order and last message in the conversation list during a real run of the app
- Sent and delivery status on the most recent message in the group

Improve fixtures, restore InboxView rendering on the test page

---

_locales/en/messages.json
about.html
app/menu.js
js/views/inbox_view.js
js/views/install_view.js
main.js
preload.js
test/index.html

Quite a few changes made in this PR
- All menu item labels provided by us (and not by built-in Electron roles) are now localizable
- There's now an About box you can get to on Windows and Linux
- The help menu now has four new items: Go to release notes, Go to forums, Go to support, File a bug
`app/menu.js` was changed radically to return a function that creates the menu based on provided 
actions and locale-specific messages. The menu creation code was also refactored to put all the Mac-related menu manipulation in one place.
Lastly, there's one little bonus in this change - when setting up a new desktop app, we now set the machine's hostname as the default device name. Only we developers have a lot of different OSes we install the app on.

Improve OS menu

---

js/background.js

We've received Linux logs indicating that we can get offline/online blips - only 30ms between the two events. The app was never really offline. So this change slows the whole disconnect process down.

Wait to manually disconnect after receiving 'offline' event

---

Gruntfile.js
appveyor.yml
fix_broken_perms.sh
package.json

We no longer use the assets built on AppVeyor for windows, so we eliminate them from `AppVeyor.yml`, the `fetch-release` Grunt task, and the `fix_broken_perms.sh` script.
Also, the new About window shows up as blank in production because `about.html` is not included in the final build. It's now included.

Fix deployment: No longer use CI windows assets, include about.html

---

js/background.js

Helps with tracking down per-version bugs when log could contain output from more than one version.

Log when we've detected a new version

---

main.js

We just don't need that many log entries about the browserwindow.

Reduce logging when the window moves

---

js/views/conversation_view.js

If you've got a slow network connection, that's no reason to make the conversation load slow.

Load profiles for a conversation without blocking convo load

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Since BitHub is broken and not coming back, the references to BitHub in the docs are obsolete and probably confusing to those who don't know that it's broken. This commit removes all references to BitHub in the repository.
See WhisperSystems/Signal-Android@258910504cc2fcc57b8868cb0ea210b21086d314

Remove all references to BitHub

---

js/libtextsecure.js
libtextsecure/api.js

We've seen some logs where some requests take more than 30s to return. This change introduces a timeout provided to `node-fetch` of 5s by default, and unlimited when dealing with large files: download or upload of an attachment, or download of an avatar.

 Add 5s timeout for all requests except attachment up/down, avatar

---

js/background.js

Because Chrome extension updates can be slow, this is a faster method of getting the Chrome app deprecation message out there.

Remotely deprecate Chrome app via file on updates.signal.org

---

js/background.js
js/libtextsecure.js
libtextsecure/message_receiver.js
libtextsecure/websocket-resources.js

We got a user log showing an overlap in online/offline events and our check to see if we were offline in the `onclose` method of `MessageReceiver`. This change prevents that kind of race condition. It also attempts to make the experience better on Linux with changing network conditions.
The changes:
- In `background.js` we stop the `disconnectTimer` even if we weren't already connected to the socket
- In `MessageReceiver` we don't try to connect again if `calledClose` is true
- In `WebSocketResource` we wait just 1s before sending our own socket `close` event
- In `MessageReceiver` we no longer `shutdown()` in `close()` - we actually wait for the socket (or `WebSocketResource` to send us the `close` event.

Better handling of online/offline behavior, socket shutdown

---

js/models/conversations.js

Turns out that sometimes a message with no errors has an empty array, and sometimes it has just null. Now we handle both.

Re-enable read receipts and read syncs

---

js/libtextsecure.js
libtextsecure/api.js

I got a 413 (Rate limit exceeded) error from the server while fetching prekeys. The client tried to parse the response as json since we expect json from the prekey endpoint, which threw an exception because the response is not json in this case.
This caused us to present the failure as a general network failure instead of a rate limit issue. The overall impact on UX was minimal, since the resend button appeared and worked as expected, but the error message was wrong.
This change prevents us from treating the response as json unless it has the Content-Type header set accordingly. If for some reason, the client and server disagree on whether the response
should be or is json, we'll default to treating it as text.
// FREEBIE

Fix json parsing exceptions obscuring server errors

---

js/notifications.js

This fix is related about issue #1587
window.drawAttention() repositioned to allow complete control over notifications by settings. It now does not draw attention when the notifications are off.
In fact, didn't do any test because I didn't set my development environment yet and the fix is too easy.

Fixed drawAttention() position to comply with user's settings

---

.travis.yml
Gruntfile.js
about.html
app/config.js
app/user_config.js
appveyor.yml
aptly.sh
js/background.js
js/conversation_controller.js
js/logging.js
main.js
package.json
prepare_build.js

To release a beta build, increment the version and add `-beta-N` to the end, then go through all the standard release activities.
The `prepare-build` npm script then updates key bits of the `package.json` to ensure that the beta build can be installed alongside a production build. This includes a new name ('Signal Beta') and a different location for application data.
As part of this, a couple new bits of data are shown across the app:
- Environment (development or test, not shown if production)
- App Instance (disabled in production; used for multiple accounts)
These are shown in:
- _The window title_ - both environment and app instance. You can tell beta builds because the app name, preceding these data bits, is different.
- _The about window_ - both environment and app instance. You can …

Beta versions support: SxS support, in-app env/instance display

---

background.html
js/database.js
js/storage.js
js/views/migration_view.js
test/database_test.js
test/index.html

This introduces a database upgrade which processes all messages with attachments, checking to see if they need a bit of help. The goal is to fix #1617 and fix #1616 (and their `InvalidModificationError` and `Invalid Buffer` errors).
The key culprits appear to be:
- no `fileName` and no `id` fields. So, if there's no string `fileName`, and `id` is not a string or number, then we generate our own unique id.
- no `data` field - we drop these attachments entirely
For good measure we also ensure that `fileName` and `contentType` are strings if they are present. Don't think these caused any problems, but why not do some quick checks?
**Bonus:** if the export process fails, we allow you to cancel out of the workflow and go back to use the app normally.

Clean up attachments with unexpected structure

---

main.js

Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1622

Don't call createWindow before the app is ready for it

---

js/backup.js
js/database.js
test/database_test.js

Because we're still getting `Illegal Buffer` errors on export, we remove all zero-length attachments.
Because previous attempts to clean up attachments didn't solve the `InvalidModificationError` errors, we log extra information to the devtools only. This will only show up for users monitoring the export with the DevTools open. It shows three things:
- Any time we try to create a directory
- Any time we try to create a file
- Any time we start writing attachments for a message, showing the message id
This should help with bug #1616

Export: remove zero-length attachments, devtools-only logging

---

_locales/en/messages.json
js/backup.js
js/views/migration_view.js

Because people are running into errors on import, or simply situations where they can't install the new standalone signal desktop, we now all cancellation of the migration.
And a little bonus: handling export errors from `stream.write()` a little bit better.

Cancel out of a complete migration

---

_locales/en/messages.json
background.html
js/backup.js
js/views/migration_view.js

Migration flow:
- The first step is now 'Install new Signal Desktop', linking to a support page which shows the supported platforms. The user can cancel out of this step.
- Subsequent steps no longer have 'Install new Signal Desktop' buttons
- The cancel button has been removed from the final 'Export complete' screen, since it allows the user to get into a very bad situation if that data is imported as well. Two competing clients with the same information. Lots and lots of errors. Some users get into that situation because they can't yet install the new standalone Signal Desktop, which is why we have our new first step. If users have trouble importing into the new standalone Signal Desktop, they can contact support and get the manual workaround.
Export:
- We now allow for duplicate …

Export: Fixes and debugging, Migration: show install step first

---

js/backup.js
js/chromium.js

To get a better handle on the export issues we're dealing with, we now continue on with the export even if we run into an attachment or malformed `messages.json`. We count up how many problems we encounter, then report that at the end of the process. If non-zero, we consider the whole export failed, but there's useful metrics in the log.
For the `Illegal buffer` issue (https://github.com/WhisperSystems/Signal-Desktop/issues/1616), we now attempt to handle these 'strange' pieces of data by first giving them to a `Uint8Array`.
For the malformed JSON issue (https://github.com/WhisperSystems/Signal-Desktop/issues/1637), we now verify the structure of every `messages.json` file before considering that conversation export done. However, I discovered that immediate checking of these files found …

Export fixes, tracking export metrics, show new versions in log

---

_locales/en/messages.json
js/backup.js

Previously we were forging ahead with more data import without waiting for IndexedDB to tell us that its transaction was complete. This may help us process large-scale imports which were previously failing after exhausting available RAM: https://github.com/WhisperSystems/Signal-Desktop/issues/1629
And we make the start screen simpler, no longer referencing 'Chrome App,' just exported data.

Wait for IndexedDB transactions to complete for import scale

---

js/backup.js
js/delivery_receipts.js
js/libtextsecure.js
libtextsecure/api.js
libtextsecure/message_receiver.js

Should help with #1669, where users are seeing a regression from the Chrome App, which didn't have a timeout for web requests. This changes our timeout from 5s to 10s.
Should also help with #1664, which talks about the number of messages downloaded on startup on the loading screen. We tend to build up more and more of these messages that need to retried, since we retry them so many times. This change makes it so we retry a message just once before discarding it. Before, it was four times.

Increase web request timeout, drop failed delivery receipts, export error logging

---

js/views/migration_view.js

We wire up Promise `reject()` methods to a number of callbacks, which means that they can provide weird things to us: non-errors. This then results in the `MigrationView` not knowing that there was an error, because it relies on the `error.message` property, which is always there if an `Error` is constructed properly. This hardens `MigrationView` to handle a promise that `reject()`s with anything.

Migration View: Handle non-errors from export process

---

_locales/en/messages.json
app/menu.js

* KDE Neon User Edition (Ubuntu Linux 16.04 core with KDE 5.11.2)
Two commits in this pull-request.
The first one added support for file menu shortcuts. This commits add a feature (#1695), and also resolves a bug (#1688).
The second commit makes the code conform to the coding style of the signal desktop app. One of the bullet points in the `Pull request` checklist mentions that we should: 
`Never use plain strings right in the source code - pull them from messages.json! You only need to modify the default locale _locales/en/messages.json. Other locales are generated automatically based on that file and then periodically uploaded to Transifex for translation.`
However, even existing code for the menu labels did not conform to that bullet point.

Added top level menu shortcuts and pull the top level menu labels from messages.json

---

js/backup.js

It appears that at some point, attachments were saved to IndexedDB in the same way that we prepare binary files for JSON:
```
{
type: 'ArrayBuffer',
encoding: 'base64',
data: '<data>'
}
```

Handle attachments previously saved in base64 format

---

js/backup.js

Our attempt to verify the structure of a just-written `messages.json` sometimes fails. It can be because the file hasn't been flushed to disk, or because we can't load the file for some reason. 
With this change, neither type of problem will stop the export, nor will they cause the export to be considered a failure. Instead, they will simply result in log entries and some overall statistics printed out at the end of the export.
This seems like the right tradeoff for debugging needs and reliable imports right after export.

Make messages.json checking stats only, don't block export

---

js/backup.js

Some logs have indicated that large amounts of data is saved to `messages.json` when a message was unsuccessfully sent and had an attachment. In this case, we open the `errors` array and delete any attachments hanging around in the cached message.

Eliminate attachment when errors saved full message details

---

main.js
package.json

This supplements the work we already do to tell the OS about our icon.
Should fix https://github.com/WhisperSystems/Signal-Desktop/issues/1649
As recommended here: https://github.com/WhisperSystems/Signal-Desktop/issues/1654#issuecomment-341436771

Add icon to the window manually on creation

---

main.js
package.json

In https://github.com/WhisperSystems/Signal-Desktop/pull/1735 we pulled the image from `/build`, but we can just load it from `/images`.

Use icon from /images for window creation

---

fix_broken_perms.sh
package.json

The files aren't always called 'Signal.app' or 'signal-desktop' anymore!

Beta builds: A few updates required for successful release

---

js/background.js
js/libtextsecure.js
js/rotate_signed_prekey_listener.js
libtextsecure/account_manager.js

I've noticed that we're not adequately resilient to questionable situations in our signed key rotation. For example, I saw a log last week where the rotation failed because of network difficulties. Today, in that case, we would wait until the next scheduled key rotation time: a couple days.
With this change, after a failed rotation, we try every five seconds until it succeeds.
In this change we also get a little more precise about when we start up the signed key rotation. It doesn't make sense to do it before the user is registered, and it doesn't make sense to do it in the middle of an import, so we only do it if registration is complete, and import is complete.

Retry failed signed key rotation; start rotation when registered

---

js/views/conversation_view.js

This mirrors the way Android does things. Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1777

Remove last seen indicator if we get a sync'd outgoing message

---

package.json

Fixes #1744
To get this bugfix: https://github.com/electron-userland/electron-builder/pull/2085

Update to electron-builder 19.29.0 for better shortcut behavior

---

js/libtextsecure.js
js/models/conversations.js
libtextsecure/api.js
libtextsecure/libsignal-protocol.js
libtextsecure/message_receiver.js
libtextsecure/sendmessage.js

We've seen a number of people complaining of `Bad MAC` errors (like https://github.com/WhisperSystems/Signal-Desktop/issues/1296) which can't be solved with a manual `reset secure session`. This brings our session reset behavior inline with the mobile apps:
- fully deleting all sessions before sending anything new, to ensure that it goes through without encryption errors
- deleting all sessions afterwards too, so all sides are starting from zero sessions when the next message is sent

Proper session reset: Delete sessions before and after

---

Gruntfile.js
about.html
app/auto_update.js
js/jquery.js
main.js
preload.js

We set the parent on the 'new update available' dialog, in the hopes that it doesn't disrupt other things happening on the machine: https://github.com/WhisperSystems/Signal-Desktop/issues/1753
A couple changes for the About Window addressing https://github.com/WhisperSystems/Signal-Desktop/issues/1750:
- The escape key can dismiss it
- It's now parented to the main window, which should make it behave a little bit better

Set parent window for about/new version, escape to close

---

js/backup.js

Contrary to the [guidance provided at MDN regarding `transaction.error`](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/error), we weren't getting an error back, at least not one that seemed to behave like a normal `DOMException` (namely: printable). From a recent log posted to https://github.com/WhisperSystems/Signal-Desktop/issues/1765:
```
INFO  2017-11-15T09:09:22.679Z saveAllMessages transaction error: {}
INFO  2017-11-15T09:09:22.679Z the import went wrong: {}
INFO  2017-11-15T09:09:22.680Z Error importing: {}
```
Either the thing we got from `transaction.error` had an empty object for its `stack` property, was an empty object itself, or we need to use a different technique to get the error when an IndexedDB transaction or request goes wrong. In this PR, we now pull …

 Move to e.target.error, transaction/request.error didn't work

---

js/notifications.js
main.js
package.json
preload.js
yarn.lock

Right now SIgnal Desktop Standalone has no notification experience for Windows 7. The beta build apparently shows one notification, and thereafter nothing. These changes, adapted from [the original PR](https://github.com/WhisperSystems/Signal-Desktop/pull/1783), get us notifications on downlevel Windows. No changes have been made to the experience on OSX, Linux, or recent versions of Windows.

Introduce library for notifications on downlevel windows

---

_locales/en/messages.json
app/tray_icon.js
main.js

This commit adds a tray icon to the application, shown in the system
tray bar, that can be used to minimise the application window.  This
is a common feature on most desktop messaging apps (e.g. Telegram
Desktop or Slack) and allows to save space in the system task bar.
The tray icon provides a context menu that contains a button to
show/hide the application window, and a button to quit the
application. When the tray icon is clicked, the visibility of the
window is toggled.  When the close (x) button of the window is
pressed, the application is not terminated but minimised to the tray
icon instead (it can be terminated by using the "Quit" entry in the
File menu or in the context menu of the tray icon).
The tray icon is disabled by default, and two command line arguments
are available to …

Add a tray icon to the application

---

main.js

Use `mainWindow.flashFrame` on platform `linux`, which was previously only done for windows and mac. For `X11` in linux, the implementation of [flashFrame uses `urgency hints`](https://chromium.googlesource.com/chromium/src/+/master/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc#1099).

add urgency hints for linux platform

---

js/background.js

https://github.com/WhisperSystems/Signal-Desktop/pull/1807 introduced some new behavior to the 'delete messages' option - it would remove the item from the left pane as well.
A new group/contact import will restore all of these contacts to the left pane. This fix addresses that - if the user has explicitly hidden an item, new import will not restore it. Only receiving or sending a new message in that conversation will re-add the item to the left pane.
-- Tested re-imports on an old installation, as well as starting a new install from scratch, and re-importing on top of that.

On group/contact import: don't re-add hidden entries to left pane

---

js/background.js
js/libtextsecure.js
js/logging.js
js/models/messages.js
js/signal_protocol_store.js
libtextsecure/account_manager.js
libtextsecure/message_receiver.js

- Log when we successfully load a signed prekey, which will help us track down prekey errors (what key id is being used by the successful incoming prekey messages?)
- Add a top-level handler for unhandled promise rejections
- Improve logging for top-level unhandled exception handler
- `removeSignedPrekey` log and ensure that promise is resolved in error cases
- Get rid of the two-log pattern for some of our error handling
- Log our handling of blocked number sync messages
Not logging, but important: Save three old signed keys in addition to the current active key. Will give us a little more breathing room, especially when a desktop client has been offline for a long time.

A variety of logging improvements to track down bugs

---

main.js

We've gotten some reports that Signal Desktop fails to appear on Windows in some cases (https://github.com/WhisperSystems/Signal-Desktop/issues/1704). Further testing indicates that Windows, unlike OSX, does not do bounds-checking when initially placing a window, which can mean that a window can be totally off-screen, inaccessible.
This PR hardens our handling of an incoming window creation parameters from `config.json` :
1) We restrict the set of data we apply to the creation of the window
2) We validate the data types of everything we load
3) We ensure that the position/size of the window results at least of 100px of visible window contents (except the top, which must be onscreen) - if none of the available displays on startup are found to result in visibility, the provided `x` and `y` …

Harden our handling of config.json, verify that window is visible

---

js/libtextsecure.js
libtextsecure/api.js
package.json
preload.js
yarn.lock

We pull proxy settings from environment variables, as requested in #1632:
- HTTPS_PROXY for sending, profile pulls, and attachment download/upload
- WSS_PROXY for connecting to the websocket for receiving messages
- ALL_PROXY to provide one server for both
More details on our proxy handling:
- https://github.com/Rob--W/proxy-from-env#environment-variables
- https://github.com/TooTallNate/node-proxy-agent
This is the natural way of things for Linux. My understanding is that most proxies on MacOS are system-wide and transparent, so it's not so urgent. But Windows will likely require further UI for configuration. Will need to do some testing with Windows users.

Add proxy support based on environment variables

---

package.json

I knew the emoji stuff was huge, just didn't realize that our filtering for the ASAR was broken! The good news is that this fix takes our packages down to smaller than they currently are in production. :0)
Beta.2: `Signal Beta.app` is 249MB
Beta.3: `Signal Beta.app` is 381MB
Now: `Signal Beta.app` is 175MB. Zip is 78.8MB, DMG is 81.1MB.

Fix ASAR filter: takes ASAR size down by ~200MB

---

app/auto_update.js

Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1864. Sadly, it will not take effect in the next release, but the release after that. The bug is in the on-disk version of the app when a new version becomes available.
Originally introduced in https://github.com/WhisperSystems/Signal-Desktop/pull/1795, which went out in `v1.0.39` and `v1.1.0-beta.2`.
It does seem to have been discussed previously in this closed issue: https://github.com/electron/electron/issues/6345#issuecomment-271055970

Delay our call to quitAndInstall(); doesn't work inside callback

---

app/auto_update.js

Fixes #1885
This prevents the user from restarting the app by pressing space on MacOS,  which happens frequently during the course of normal typing of a message.
In the future we'll move to a less-obtrusive system a little more like Chrome, where you choose to do the restart when it is convenient for you. For now, we minimize the chance of accidental restart in the middle of typing a message.

Update available dialog: default is now 'later', not 'restart'

---

package.json
yarn.lock

Fixes #1892
In many cases this removes generic emoji in favor of new gendered
options (one of which was a copy of the previous generic emoji anyway).

Remove obsolete emoji via a new fork of emoji-panel

---

main.js

* MacOS 10.12.6, Chrome 62.0.3202.94
This is a very small change, but allows the chat window to better fit into smaller spaces (e.g. tiled window managers)
The previous Chrome app version had a min-width of 650px. I figured 640px might be a little better, although I'd be happy with either over the current value of 700px, which no longer fits into the space I had assigned it to.

A slightly more reasonable min-width

---

package.json

* Debian docker image on Arch 4.14.3-1-ARCH
Adds `libasound2` and `libxss1` to the generated `.deb`'s dependencies, as well as the [default `.deb` dependencies](https://www.electron.build/configuration/linux#debian-package-options) included by `electron-builder` (`["gconf2", "gconf-service", "libnotify4", "libappindicator1", "libxtst6", "libnss3"]`).
Probably fixes #1838, but @angelo-v should probably test this out first, since I can't get my docker setup to open windows on my host OS.

Add .deb specific dependencies

---

main.js

Fixes #1877
We now use the same logic to show the window in the 'show-window' ipc handler and the second instance handler.

Show window if hidden when second instance attempts to start

---

js/views/attachment_view.js
js/views/file_input_view.js

Fixes #1713.
iOS renders my test tiffs properly, but Android `v4.14.7` just shows an empty square.

Treat tiffs like unrecognized files; Chrome doesn't render them

---

main.js

Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1916
We had a regression in Windows window management during the last few weeks, related to branch merges and tray support.

Remove duplicate showWindow method

---

js/backup.js
test/backup_test.js

This should give us the information we're looking for when imports fail
mysteriously! Like in this bug: https://github.com/WhisperSystems/Signal-Desktop/issues/1765
DOMExeptions are a little strange: https://developer.mozilla.org/en-US/docs/Web/API/DOMException

Log out information from DOMException when import fails

---

js/views/conversation_view.js
js/views/recorder_view.js

Addresses the problematic send behavior discussed in #1933 by being more strict about the handling of the message composition field. Previously, any click would clear the `disabled` attribute.
Also, get consistent with our treatment of the `disabled` attribute.
Finally, add some comments explaining how the audio recording dismissal works if you click in a random place on the screen. It turns out that `InboxView` reaches in and triggers its 'close' event!

Preserve disabled state in the middle of sending message

---

js/libtextsecure.js
libtextsecure/errors.js
libtextsecure/test/index.html

No more errors like this in the logs!
```
INFO  2018-01-05T18:33:15.942Z Message.saveErrors: null Error
at file:///C:/Users/Test/AppData/Local/Programs/signal-desktop/resources/app.asar/js/libtextsecure.js:30:33
at file:///C:/Users/Test/AppData/Local/Programs/signal-desktop/resources/app.asar/js/libtextsecure.js:138:3
at file:///C:/Users/Test/AppData/Local/Programs/signal-desktop/resources/app.asar/js/libtextsecure.js:40718:3
```
It has no information in the title, and then the callstack points to the `new Error()` line in the old `errors.js`.
This change will include the actual error name and message details in the stack, and will include the original http error stack as well if provided.

Make errors more debuggable; capture correct stack, include name

---

CONTRIBUTING.md

* This is a change in documentation
See #1835. Testing out the build system is currently undocumented, but this PR adds some instructions to `CONTRIBUTING.md` for building/testing new releases.

Document building/testing releases

---

js/signal_protocol_store.js
libtextsecure/sendmessage.js

A couple quick changes:
- turns out that the device id was actually a string in my testing, so we change it back to `==`
- our prekey fetch logging had a bug in it - it didn't differentiate between prekeys and signed prekeys.

Fix device ID check, clean up prekey fetch logging

---

js/conversation_controller.js
libtextsecure/api.js

Two primary changes in this pull request, both inspired by https://github.com/WhisperSystems/Signal-Desktop/issues/1964:
- When a group comes in with a number we don't understand, we currently fail quite spectacularly. With this change, we will note the invalid number in the log, and add the contact to the `ConversationController` without saving to the database. This will allow most scenarios to move forward without interrupt.
- When we get an error from the server, or when a web request fails, we generally drop the original error's information, preferring to use our own error messages and the stack on the way in to the original web request. This change brings back some of that key information to ensure that our logging in these cases is a bit more useful.

More information on http errors, resilient to invalid group members

---

js/views/conversation_list_view.js

We recently received a number of reports saying that the left pane would stop sorting, or that it was wrong. This change introduces two changes to help with the sorting of that left pane:
1. If we reach any invalid states, where the target conversation isn't yet added to the DOM, or we can't figure out where it is by index, we log and in some cases fully bail out
2. our previous technique of trying to discover the location of the current conversation in the DOM by index seems to be incorrect. My investigation seems to indicate that it was returning `-1` for the index all the time. Pulling the full set of conversations then checking the index against that does seem to work, however. This may help make our sorting a little less error-prone.

Left pane: small sorting fix, logging for error cases

---

js/views/attachment_view.js

Fixes #1963, which reported a video which could not be played back after being forwarded by Android. The problem stems from Android's use of the content-type 'video/*', which the browser treats as invalid, skipping the `<source>` entry entirely.
If we omit the `type` parameter to the `<source>` tag, the video plays. So this is a bullet-proofing fix. The right fix, which will give us a good filename, is for Android to fix how it forwards media.

Video/audio: rely on the browser to detect content type

---

js/signal_protocol_store.js
libtextsecure/account_manager.js

A recent log posted in https://github.com/WhisperSystems/Signal-Desktop/issues/1273#issuecomment-358386670 indicated that we weren't handling signed prekeys properly when a new account was created (either initial setup or re-link). This change does two things:
1. We clear out all local prekeys and signed prekeys as part of the account create process
2. We confirm the new signed prekey registered with the server right as part of the account create process

Account setup: confirm first signed prekey, clear all prekeys

---

js/views/conversation_view.js
libtextsecure/message_receiver.js

fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1951
Likely also fixes #1957
This fixes a race condition where:
1. The user had selected to show a conversation, and that resulted in a database fetch.
2. During that fetch, a message in that conversation expired. That expiration reached out to the `ConversationView` to remove it from the UI.
3. The database fetch completed, including that expired message.
This ensures that the UI removal happens after any pending database fetch.
Note: tested with an artificially-extended `fetchMessages`, and the issue both repros reliably and is fixed with these changes.

Remove expired message if it expired during database fetch

---

package.json
yarn.lock

Fixes #1991, related to IME input on Mac.

Update to latest Electron 1.7.x

---

_locales/en/messages.json
js/background.js
js/models/blockedNumbers.js
js/models/conversations.js
js/views/message_view.js
protos/IncomingPushMessageSignal.proto

The conversation `expireTimer` and contact block status has been added to the ProtoBufs in the java repo: https://github.com/WhisperSystems/libsignal-service-java/commit/c8d7c3c00445a81b81e0a7305151cda4534ba299
These changes add support for this new data included in these sync messages, but this PR will need to wait for testing against the Android and iOS implementations.
Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1959
Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/944
Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1433
Fixes https://github.com/WhisperSystems/Signal-Desktop/issues/1543

Process expireTimer and block status along with contact/group sync

---

main.js

In the case where we've detected we're the second instance, we activate the primary instance then exit. On Windows this scenario was causing an error dialog to pop up, because we were using `app.quit()`, which doesn't close the app immediately. `app.exit()` does.
Fixes #2016

app.quit() -> app.exit(), immediate app close on second instance

---

main.js

Protect against null mainWindow in captureAndSaveWindowStats

---

js/models/conversations.js

Turns out `textsecure.messaging` is only set up on first connection to the server. When we start up offline, we never do that. And it prevents the user from opening every conversation.
There's a whole lot more to do to bulletproof ourselves against a missing textsecure.messaging (and then beyond that, queuing outgoing messages so they don't get dropped completely when offline).
Hence, this is just a band-aid.

Enable conversation open when app started offline

---

js/views/app_view.js
js/views/install_view.js

First, we now clear data on finish of new install, unless it's a re-link/light import.
Why? From the comments:
> Delete all data from database unless we're in the middle
> of a re-link, or we are finishing a light import. Without this,
> app restarts at certain times can cause weird things to happen,
> like data from a previous incomplete light import showing up
> after a new install.
Second, we no longer show setup options in file menu in middle of a light import.
More justification from the comments:
> If we're in the middle of import, we don't want to show the menu options
> allowing the user to switch to other ways to set up the app. If they
> switched back and forth in the middle of a light import, they'd lose all
> that imported data.

Two fixes for tricky import/register scenarios

---

.github/ISSUE_TEMPLATE.md
README.md
main.js

We recently changed our forum URL from https://whispersystems.discoursehosting.net/ to https://community.signalusers.org/. This change updates all our references in the app.

Update links to community forum

---

js/background.js
js/models/conversations.js
js/models/messages.js

iOS omits `expireTimer` protobuf property to denote disappearing messages have been turned off. However, that doesn’t allow us to distinguish it from old clients that are not aware of this property. This change ignores these invalid values until we consistently use `0` to denote disabled disappearing messages.

Hotfix: Ignore invalid expire timer sync resets

---

js/models/conversations.js

When you link a new device, as of `v1.5.0` we get the disappearing messages status along with the initial contact/group sync. But this currently pops all conversations with a timer change to the top of the left pane. This change prevents that.

Don't pop conversations with timer change to top

---

app/menu.js
stylesheets/_global.scss

Two fixes to the import/registration workflow screens.

Show View -> Debug on OSX, ensure Debug Log is visible

---

yarn.lock

To update the following dependencies…
- electron-updater
- electron-builder
- electron-publisher-s3
- spectron
…`package.json` was mistakenly updated manually which prevented an update
of `yarn.lock`.
This change brings them in sync.

Update `yarn.lock` after manual `package.json` changes

---

.travis.yml
CONTRIBUTING.md
appveyor.yml

As recommended by documentation:
> If you need reproducible dependencies, which is usually the case with the
> continuous integration systems, you should pass `--frozen-lockfile` flag.
-- https://yarnpkg.com/lang/en/docs/cli/install/

Ensure consistent builds using `yarn --frozen-lockfile`

---

app/menu.js
test/app/fixtures/menu-windows-linux-setup.json
test/app/fixtures/menu-windows-linux.json

As discussed, `Ctrl+,` is not idiomatic on Windows & Linux.

Remove ‘Ctrl+,’ keyboard shortcut on Windows & Linux

---

background.html
js/views/install_view.js
stylesheets/_global.scss

The recent redesign of the registration flow got rid of a `<form>` tag, which meant that you can no longer move to the next step in the process by pressing enter after entering your device name. This PR restores that behavior.

Choose device name screen: Finish by pressing enter

---

.eslintignore
js/background.js
js/logging.js
js/views/attachment_view.js
js/views/debug_log_view.js

Manual changes: https://github.com/signalapp/Signal-Desktop/pull/2111/files/77cc9b61c9e0ec4a4091e6e65e1096da3b6ee314..0cf64f5083263b44e12e6625fe14bef7a72e070c

Autofix: Move Debug Logs From GitHub Gists to debuglogs.org

---

Gruntfile.js
_locales/en/messages.json
app/menu.js
js/focus_listener.js
js/logging.js
js/modules/debuglogs.js
js/views/debug_log_view.js
package.json
stylesheets/_debugLog.scss
test/app/fixtures/menu-mac-os-setup.json
test/app/fixtures/menu-mac-os.json
test/app/fixtures/menu-windows-linux-setup.json
test/app/fixtures/menu-windows-linux.json
test/modules/debuglogs_test.js
yarn.lock

In anticipation of GitHub’s deprecation of anonymous gists, we are moving our debug logs to https://debuglogs.org.
**Sample log:** https://debuglogs.org/0272bdd35288ed839ede88938a5290011150d42b56599efb5dd93ac80a2ac915

Move Debug Logs From GitHub Gists to debuglogs.org

---

background.html
js/debugLog.js
js/views/migration_view.js
manifest.json

In anticipation of GitHub’s deprecation of anonymous gists, we are moving our debug logs to https://debuglogs.org.
- ~~Using jQuery v2.1.1-pre results in S3 error about invalid form data indicating our jQuery version (added in 2014) doesn’t serialize `FormData` correctly.~~
**Sample log:** https://debuglogs.org/76bf1d7fd9b88ad061d91f79914230e45dc123bc8d169e073f10adb5c1999d4e

Chrome: Move Debug Logs From GitHub Gists to debuglogs.org 

---

main.js

Simple change to ensure that a webview is never created. Since we don't run third-party javascript and have a strong CSP, this will never happen - we're adding it for future-proofing.

Disable all webviews, since we never intend to create them

---

background.html

https://github.com/signalapp/Signal-Desktop/issues/2127 reported that after an export error happened, neither of the two buttons could be clicked. With this change, they are now clickable.

Make 'submit debug log'/'try again' clickable on error screen

---

stylesheets/_ios.scss

Fixes small regression from https://github.com/signalapp/Signal-Desktop/commit/ef041b29d0b1b1dc5e9ed3ede76d7ef48bdb71cb
**Before**
**After**
/ht @michaelkirk

iOS Theme: Ensure conversation panel fills screen vertically

---

stylesheets/_ios.scss

@scottnonnenberg Your previous observation was correct and my original attempt to fix this cut off the first message in a thread. This change seems more robust and handles that correctly.
Follow up to #2144.
Fixes #2149.

iOS Theme: Ensure first message is not cut off

---

.github/PULL_REQUEST_TEMPLATE.md

Some of our users submit direct PRs against our translations. This update to our PR template is meant to encourage them to contribute translations via Transifex.
Prompted by this user PR: https://github.com/signalapp/Signal-Desktop/pull/2156

Request translation changes to be made via Transifex

---

CONTRIBUTING.md
background.html
test/index.html

Fixes #2043. The notification that is shown when an installation is expired referred to the Chrome web store - it now refers to Signal.org/download. I tested this manually by setting changing the expiry check to `if(true)` and then clicking the update button. Note that I wasn't quite clear on what `index.html` did, so while I did change it I wasn't able to test that. I tested this on:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```
I also fixed a typo in the contribution guide, and specified that one has to rebase off of `development` instead of `master - because that is what is specified in the PR template.
Note that I'm aware that you usually first have to specify your intention to contribute …

2043 expiry message

---

Gruntfile.js
js/conversation_controller.js
js/views/conversation_search_view.js
test/keychange_listener_test.js
test/views/message_view_test.js

When typing in an existing phone number into the search, clicking on it even though there exists an existing contact will reinitialize that contact’s database entry. This reinitialization clears that contact’s conversation’s name, unread count, etc.
This change ensures we always reuse existing conversations using `ConversationController.getOrCreateAndWait` when starting new conversations in the search view.

Fix contact overwrite in search view

---

package.json

What the title says. This is particularly problematic because Yarn apparently errors (not warns) if the engine doesn't match; I just had a friend complain about this in a group chat.

Don't lock the Node version so strictly

---

js/background.js
js/modules/settings.js
js/modules/startup.js
package.json
preload.js
test/modules/startup_test.js
yarn.lock

Users lose their read receipt setting after relinking their app. See: https://github.com/signalapp/Signal-Android/issues/7535
**Manual Tests**
- Started app and set read receipts on iOS.
- Sent message from another device with read receipts enabled.
- Confirmed messages were marked read on both sides.
- Unlinked primary device.
- Relinked primary device.
- Sent messages between primary and other device.
- Confirmed read receipts are still shown.
- Confirmed logs show configuration sync.

Request Configuration Sync After Relink

---

app/attachments.js
js/modules/backup.js
js/modules/types/attachment/migrate_data_to_file_system.js
js/modules/types/message.js
preload.js
scripts/start-backup
test/app/attachments_test.js
test/modules/types/attachment_test.js
test/modules/types/message_test.js

**Tests**
**Test commands:**
```javascript
// Export
let key = new Uint8Array([1, 3, 4, 5, 6, 7, 8, 11, 23, 34, 1, 34, 3, 5, 45, 45, 1, 3, 4, 5, 6, 7, 8, 11, 23, 34, 1, 34, 3, 5, 45, 45]);
Signal.Backup.exportToDirectory('/Users/<user>/Desktop/Signal-import-export-test', {key});
// Import
let key = new Uint8Array([1, 3, 4, 5, 6, 7, 8, 11, 23, 34, 1, 34, 3, 5, 45, 45, 1, 3, 4, 5, 6, 7, 8, 11, 23, 34, 1, 34, 3, 5, 45, 45]);
Signal.Backup.importFromDirectory('/Users/<user>/Desktop/Signal-import-export-test', {key});
// Import from Chrome
Signal.Backup.importFromDirectory('/Users/<user>/Desktop/Signal Export 2018 Apr 3 at 11.00.54 pm');
```

Support Attachments On File System During Export + Import

---

js/views/migration_view.js
stylesheets/_global.scss
stylesheets/manifest.css

Some of our users skipped over the installation screen as it wasn’t clear installation was a required action before proceeding.

Hide “It’s Installed” until user installs standalone version

---

.eslintrc.js
app/attachments.js
js/conversation_controller.js
js/modules/backup.js
js/modules/database.js
js/modules/debug.js
js/modules/messages_data_migrator.js
js/modules/migrations/run_migrations.js
js/modules/privacy.js
js/modules/settings.js
js/modules/startup.js
js/modules/string_to_array_buffer.js
js/modules/types/attachment.js
js/modules/types/attachment/migrate_data_to_file_system.js
js/modules/types/message.js
test/modules/privacy_test.js
test/modules/types/message_test.js

Redact More Variants Of Paths In Stack Traces

---

stylesheets/_ios.scss

We discovered that iOS quote bubbles rendered incorrectly only on some machines. But this change should fix it, either way.

Add border-radius to iOS quoted-message to fix MacOS render bug

---

_locales/en/messages.json
ts/components/conversation/Quote.tsx

Instead of pulling information from the user's contacts (which doesn't always have their own contact set), we now show 'You' for quotes referencing the current user in the android theme. This mirrors 'Replying to Yourself' or 'Replying to You' shown in the iOS theme already.
Before:
After:

Show 'You' in Android theme quotes instead of contact name

---

js/modules/idle_detector.js

This will speed up the attachment migration for existing users. Tested it locally and didn’t notice any negative impact as we still require 20ms time remaining from browser. We can tune this value based on beta user feedback.

Increase attachment migration conversion speed by a factor of 3x

---

js/modules/types/attachment.js
js/modules/types/message.js

Turns out that our JPEG auto-orient code already strips all image metadata.

Strip Image Metadata

---

.editorconfig
js/notifications.js
ts/test/types/Settings_test.ts
ts/types/Settings.ts

Grouping of notifications is not supported on Windows 7 due this bug: https://github.com/electron/electron/issues/11189

Windows 7 Notifications: Disable Grouping

---

js/views/message_view.js

Sometimes you can't click on the quotation of a given message. A restart generally fixes it.
It turns out that any message sent by Desktop would be rendered without its unique `id` attribute, because we hadn't roundtripped with the database. And we had no machinery to go update that `id` attribute after the fact. Now we do. On any `change` event (which fires after that database roundtrip completes), we will add the proper `id` attribute. Yes, it is redundant, but I don't think checking for the existence of the id before adding it again would buy us very much.

MessageView: Add id from database to DOM for outgoing messages

---

js/views/conversation_view.js

Close Emoji Panel on Escape Key Press (Refactor)

---

ts/OS.ts

Previously OS.isWindows checked if the windows version matched the one required. This worked fine, except for the fact that it would end up comparing a linux kernel version to a windows version as it didn't check if the platform was Windows in the first place before.
This caused issues as it would throw an error when comparing with non-semver Linux kernels (such as Fedora). Tests would fail and notably the settings/preferences dialogs would fail to open. Now it checks if the current platform is Windows first, and if not, immediately returns false.
All tests pass now (previously on first checkout they failed on my system), and the preferences dialog successfully opens. No errors can be found in the console.
My OS is Fedora 28 x64.
Fixes: #2396

Modify OS.isWindows to check platform before version

---

_locales/en/messages.json
js/views/conversation_view.js
js/views/message_view.js
stylesheets/_conversation.scss
stylesheets/android-dark.scss

1. We were always showing the 'Send message' button, even if the contact didn't have a Signal account
2. Contact method headers were not visible in dark theme
3. A very long contact will cause the contact details pane to break out of its container, make the whole thing scroll

Contact account detail fixes

---

js/background.js
js/models/conversations.js
js/models/messages.js
js/read_syncs.js

Fixes #2371
On a bulk read sync, we could sometimes mark older messages read in bulk. Depending on the order of the messages in the multi-message read sync, this might never happen, might happen all the time. Now we pipe the `read_at` value through to this bulk marking of messages read, ensuring that the message's expiration is properly calculated.

Ensure that messages expire at the proper time

---

stylesheets/_ios.scss

iOS theme: Links in quotes now blue (not white) for visibility

---

README.md

The previous instructions were a bit terse.

Clarify beta install instructions

---

js/models/conversations.js

A recent change removed the `type` property to make `markRead()` behave properly, but that broke our 'should we send an update?' logic. So instead of using `isIncoming()` we now use what we previously used to determine whether a message was incoming: `receivedAt`.
Fixes https://github.com/signalapp/Signal-Desktop/issues/2472
Bug introduced here: https://github.com/signalapp/Signal-Desktop/commit/dfa1f0797c243fc6763423cece99285a2fc79657#diff-e7ea6b899ac298e9faa100a737a9b5a9L885

Expire timer updates: don't send if updated via remote message

---

js/background.js
js/modules/idle_detector.js

Turns out that since `emit()` calls its handlers synchronously, we were attempting to turn everything off and then right after that a `setTimeout()` was scheduled to turn everything back on. Now the idle detector really turns off!

Idle detector: Fix bug preventing it from ever turning off

---

package.json

Turns out that we continue to have problems with with version number in the about window. This time the production build had a bug that the development builds did not.
Fixes #2463 (for reals)

Include about_preload.js in production builds

---

js/background.js

Spell check does not load if certain directories are mounted 'noexec' on linux. This change ensures that the recent feature to allow disabling spell check doesn't prevent startup of the app.
Fixes https://github.com/signalapp/Signal-Desktop/issues/2546

Workaround for linux w/tmp mounted as noexec

---

stylesheets/_modules.scss

Adding auto text alignment property (`text-align: start`) to message container, for better RTL messages view:
Instead of:

Fix text alignment for RTL messages

---

settings.html

The tiny pull request fixes unclickable checkbox labels in settings

Fix unclickable checkbox labels in settings

---

js/views/conversation_view.js

Fixes #2988. Literally removed two characters.
It seems that the line in question originally was using the equality (`==`) operator to compare the numeric `selectionStart` with the string `'0'`, but at some point was changed to the identity operator (`===`) without paying attention to the types being compared, thus the comparison always evaluates to `false`, resulting in emoji being appended to the end of the message when the caret is actually at the start. Changing the string value to a number restores the correct behavior.
Tested on Windows 10 x64.

Fix comparison for emoji injection at cursor location

---

js/models/conversations.js

Fixes #3001. The notification icon was inconsistent with the rest of the Signal app in that it used the first character of the conversation title when there was no profile image. The `Avatar` component used in the app UI uses a `getInitials` function to remove all non-word characters from the name, then gets up to two initials from the remaining word characters. This caused the icon shown in the notification to be different from the one shown everywhere else in the app window in cases where the user had two words in their name ("Mike Smith" would show as "MS" in the app, but only "M" in the notification) or if there were emoji or other characters in the name (":smile: Mike Smith" would show as "MS" in the app, but as ":smile:" in the notification).
The existing `getInitials` function is …

Make notification initials consistent with Avatar component

---

app/tray_icon.js

Fixes #2001 by making the behavior of Signal similar to Slack/Discord. If the tray icon is clicked, the window will be shown and brought into focus. Clicking the icon never hides the window.
Tested on Windows 10 x64.

Change tray icon click to always show/focus window

---

stylesheets/_global.scss
stylesheets/_index.scss
stylesheets/_modules.scss
stylesheets/_settings.scss

This PR fixes #2839 by preventing various UI elements from being selected when the user selects all text on screen. 
**Before the fix:** The top status message, entire sidebar contents, recipients avatar alt text, (hidden) context menu contents, and other elements would be selected and copied when user presses `Ctrl/Cmd+A` and then `Ctrl/Cmd+C`. 
**After the fix:** Only text within message bubbles (including timestamps), conversation status texts, and the recipients name and phone number are selected and copied. 
_Conversation View_ before/after screenshot:
This PR in turn also fixes #2274 because it prevents the sidebar from being selected via `Ctrl/Cmd+A` or mouse selection. I also extended the selection prevention to the conversation placeholder ('Welcome to Signal') view, settings …

Fix issues regarding selection and text in the UI

---

background.html
index.html
main.js
stylesheets/_global.scss

(Fixes #1410 and fixes #2925)
This PR is an attempt to fix a visual annoyance when the app starts up. When Signal (ie. Electron) starts up, a white FOUC (Flash Of Unstyled Content) occurs, because the initial page being rendered is a plain HTML file without styling. The assets are only loaded afterwards and those render the Signal logo and a loading text. This is specially awkward for those who use the dark theme (like myself) who are treated to a blindingly white screen for a few seconds before the assets and user settings are loaded, switching the theme to that pleasant dark mode.
I dug around the issues and found two other instances of this being discussed. First as a bug in #1410 and more recently as a feature request in #2925. 
In #1410, @scottnonnenberg-signal lays out why …

Get rid of the white flash when the app starts up

---

package.json

As requested in https://github.com/signalapp/Signal-Desktop/issues/2344#issuecomment-466486594
> @scottnonnenberg-signal
> Maybe one of you can do a little bit of testing/investigation and submit a tiny PR for the next beta?
I tested this by
* removing the `gconf2` and `gconf-service` dependencies from `packages.json`
* uninstalling all gconf packages from my system (Ubuntu 18.04)
* compiling the client and running it 24 hours (and counting)
* then on a fresh Ubuntu 18.04 docker container¹
* installed `signal-desktop_1.22.0-beta.2_amd64.deb` with gconf dependencies untouched
* installed `signal-desktop_1.22.0-beta.2_amd64.deb` with gconf dependencies removed on top of the previous package (i.e. updated)
* removed the signal-desktop package
No errors encountered.
¹) See full log of this …

Remove gconf dependency

---

ts/util/emoji.ts

This turns on the `allow_caps` flag on `js-emoji`’s `EmojiConvertor`, which you can see the effect of in [the tests](https://github.com/iamcal/js-emoji/blob/762bd59586ba6f5e15b4065e897266094cde6ff9/test/colons.spec.js#L43). I’m suggesting this because I’ve on occasion been holding shift too long after typing the initial colon for an emoji and sending people messages containing things like `:Laughing:`. It seems friendlier to try to interpret everything between colons as a possible emoji name, rather than ignoring things because of case-sensitivity.
I chose not to add a test for this because it seemed redundant to be testing `js-emoji`’s functionality, but it would be pretty easy if that’s desirable.
Thanks for this application, it makes it much easier to message my friends while I’m …

Add allow_caps option for emoji conversion

---

app/menu.js
test/app/fixtures/menu-mac-os-setup.json
test/app/fixtures/menu-mac-os.json
test/app/fixtures/menu-windows-linux-setup.json
test/app/fixtures/menu-windows-linux.json

* [ X ] I have read the [README](https://github.com/signalapp/Signal-Desktop/blob/master/README.md) and [Contributor Guidelines](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md)
* [ X ] I have signed the [Contributor Licence Agreement](https://signal.org/cla/)
* [ X ] My contribution is **not** related to translations. _Please submit translation changes via our [Signal Desktop Transifex project](https://www.transifex.com/signalapp/signal-desktop/)._
* [ X ] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [ X ] My changes are [rebased](https://medium.freecodecamp.org/git-rebase-and-the-golden-rule-explained-70715eccc372) on the latest [`development`](https://github.com/signalapp/Signal-Desktop/tree/developm …

Remap zoom to Command+= on macOS

---

Gruntfile.js

When running `yarn grunt dev`, as described in CONTRIBUTING.md, and changing a file with the `.tsx` extension in e.g. /ts/components, those changes are not detected by the watch task. So I added these files to the `transpile` section of `Gruntfile.js`, now changes in .tsx files are automatically detected.

Gruntfile.js: add .tsx files to watch task

---

stylesheets/_variables.scss

The default fallback font for Chinese charaters on Windows is SimSun,
which is old and not actually a sans-serif font.
And looks very different from the English alphabets.
With this commit:

Add font fallback candidates for CJK characters

---

js/views/settings_view.js
settings.html
ts/test/types/Settings_test.ts
ts/types/Settings.ts

The "Hide menu bar" option is only applicable to Windows and some Linux distros,
where the menu bar is attached to the Signal window. Therefore, this commit
ensures that it doesn't show up on MacOS. It includes a setting,
isHideMenuBarSupported(), to control the option's appearance. This
commit also includes the tests to make sure isHideMenuBarSupported()
works correctly.
Fixes #2705
Testing methodology is as follows:
- Since I'm on a Mac, I made sure that the option didn't show up for me:
- I also wrote some new settings tests for isHideMenuBarSupported, which checked to make sure it returns true on Linux and Windows, but false on Mac.

Hides the "Hide menu bar" option on MacOS (attempt #2)

---

package.json
prepare_beta_build.js

Fixes: #3387
This ~~hopefully~~ fixes: #3387
Include `desktopName` field in `package.json`, this should allow electron to properly set badge count on Linux. This should make it easier for users to see that there new messages. 
~~Have not been able to test because of: https://github.com/signalapp/Signal-Desktop/issues/3389~~
I've now been able to test this.

Include desktopName

---

ts/state/selectors/conversations.ts
ts/types/PhoneNumber.ts

As in my other PR #3395:
I haven't marked the `yarn ready` but everything passes except that I get two questionable lines in `yarn lint-deps`. I assume this is because I'm building against my system electron and node. Note that I haven't touched the deps.
(Maybe I'm too stupid to use the linters, I don't know -- I'm not a javascript guy.)
The left pane is regenerated in `_getLeftPaneList` after every sent or received message (I think even when downloading messages initially).  This regeneration step is very expensive on my configuration. Almost all of the time is spent sorting the array of conversations using a somewhat expensive comparison function, which sometimes needs to format phone numbers, and will format the same phone number multiple times (when it is compared to another multiple …

Improve performance of _getLeftPaneList

---

package.json
prepare_beta_build.js

Reverts signalapp/Signal-Desktop#3390, which appears to be causing linux builds to fail to startup properly.

Revert "Add desktopName to package.json to fix linux badge"

---

ts/components/emoji/lib.ts
ts/test/components/emoji/lib_test.ts

Hello again! This pull request brings back the change in #2353 to properly recognise colon-syntax emoji that have mistakenly-typed capital letters in them, an easy error to make when holding the shift key slightly too long after typing the colon. This was lost when 0e9d549 replaced the emoji picker.
This time, I’ve included tests that make assertions on the `replaceColons` function’s existing behaviour and a test that ensures it now ignores case when searching for known emoji short names.
Here’s a GIF of what it’s like without this change:
This is what it’s like in the development environment with this change:
I’m running macOS 10.14.4. The tests on Travis are [failing as of the most recent commit on `development`](https://travis-ci.org/signalapp/Signal-Desktop/builds/551872947) but you …

Update search for colon-syntax emoji to ignore case

---

js/modules/link_previews.js

The `SUPPORTED_MEDIA_DOMAINS` regex whitelist, used to check if media link comes from a trusted (whitelisted) host is invalid. As in e.g. `redd.it` it uses `.` character between the TLD and domain label, and this character, when used in regexes, matches any character. As a result, the whitelist matches untrusted URLs like `https://redjit/` or `https://reddXit/`.
It seems this does not expose a direct security risk as of now or I couldn't find an example of such. However, if an attacker would control a DNS server we use, they could serve content from domains that bypass the whitelist.
Another problem with the current approach are future changes: a developer that adds e.g. `media.somenewcoolcdn.net` URL would likely add it in the same format, thus, enabling direct security risk, as an …

Fix SUPPORTED_MEDIA_DOMAINS regex whitelist

---

package.json

So I stumbled upon https://www.omgubuntu.co.uk/2019/07/material-shell-tiling-gnome-shell-extension/amp today. Installed it and took it for a test drive, switched through all desktops, one of which is for social and it had all my messengers but Signal.
I figured to take a look at that and it did not seem to be a problem in the material shell, as it's not having a list of apps. So I checked signals and riots code and found this over at riot. 
https://github.com/vector-im/riot-web/blob/develop/package.json#L171
I haven't tested this, but it seems to be nothing that can hurt.

Add InstantMessaging and Chat categories for deb package

---

_locales/en/messages.json

What's New in #3470
- I have fixed a typo related to the word `safety`, so that your safe intentions aren't mistyped.

Fix typo: `saftey` -> `safety`

---

app/sql.js

I haven't marked the `yarn ready` but everything passes except that I get two questionable lines in `yarn lint-deps`. I assume this is because I'm building against my system electron and node. Note that I haven't touched the deps.
This improves the performance of database query which is run once at startup significantly.
Before:
`SQL channel job 170 (getOutgoingWithoutExpiresAt) succeeded in 533ms`
After:
No such line, i.e., < 10 ms. I think it was actually 1ms when I had enabled DB profiling.
The SQLite docs say that we should use "INDEXED BY" only if nothing else helps but I tried their entire checklist, and yes, nothing else helps... (See https://www.sqlite.org/queryplanner-ng.html#howtofix)
Related issues: #3010, #3171, #3172.

Improve slow DB query using INDEXED BY

---

yarn.lock

~* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md#tests))~ N/A
To test I nuked `node_modules/` and ran `yarn install --frozen-lockfile` again. Everything worked fine.

Fix a dep getting pulled over HTTP

---

ts/updater/common.ts

Users expect closing/cancelling a dialog box to cancel or otherwise prevent or postpone any action. Currently, when the "update available" dialog is closed by pressing `Esc` or clicking the close button, Signal proceeds with the update rather than postponing it. This corrects that unexpected behavior by making closing the dialog the equivalent of clicking the "later" button.
Fixes #2831.

Use later button as cancel behavior

---

js/background.js

Control-Command-F is a [well-known](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/) shortcut on macOS to enter and exit full screen. Unfortunately the shortcuts for `Search` and `Search in conversation` were capturing the shortcut via Command-F. The change identifies whether Command and Control are both engaged, as opposed to just either, and ignores the key event so full screen can toggle instead. I've tested manually on macOS 10.15.3 and Ubuntu 18.04.

Fix macOS full screen shortcut

---

js/spell_check.js

Previously when the user has the spellchecking setting turned off the context menu would flash instead of showing it on selected text of the conversation timeline. This behavior is due to the attempt of creating a context menu of different scope(`Editor`) on top of the targeted one.
This commit ensures proper context menu when spellchecking is turned off.
Fixes #3976

Fix context menu when spellchecker is off

---

package.json

The current `electron-builder` configuration in `package.json` includes native node modules in the asar archive. When Electron then runs the app it unpacks the native modules and then executes them. This triggers some kind of malware check in macOS and results in the OS making requests to Apple servers. In addition to the privacy issue, the app startup is delayed while these requests are in progress and isn't opened until they are either complete or timed out. This can result in a >1 min delay.
I've solved this by adding an option to the electron-builder configuration which prevents native modules from being included in the asar archive.
The difference in the the built app is that `node_modules/curve25519-n/build/Release/curve.node` and …

Prevent macOS from making requests to Apple every time the app is started

---

js/views/app_view.js
sticker-creator/preload.js

#3826 # First time contributor checklist:
Fixes #4098
The default theme settings is "system" but the `theme-setting` getter was returning `light` if no setting was returned. This PR updates the `theme-setting` getter to return `system` by default and match the default radio selection in the theme settings menu.
Tested with Desktop App on macOS Catalina 10.15.3
Ran app with system theme setting as dark, observed the app ran in dark mode. Tested changing settings worked
Deleted ~/User/Application\ Support/Signal-development
Ran app with system theme setting as light, observed the app ran in light mode. Tested changing settings worked

Fixes 4098 Default theme settings getter returns system if no setting is set to match default theme setting

---

CONTRIBUTING.md

yarn icon-gen is not in package.json and is not used anymore

yarn icon-gen script is not used anymore, removed from CONTRIBUTING.md

---

stylesheets/_modules.scss

Fixes #3168
This CSS rule was causing conversation header text to be truncated even when there was enough white space to display the entire text at certain zoom levels and platforms, as reported in #3168.
With this fix, the conversation header is no longer truncated unnecessarily. When there is an actual lack of space, truncation behaves as expected.
Testing was performed by opening the developer tools for the Signal Desktop window and switching off that CSS property, then manipulating the window to observe how the header text reacted. The expected truncation behavior was seen during:
- Changing zoom level
- Window scaling
- Changing the length of the header text
Operating systems tested on: 
- Chrome OS 81.0.4044.103 
- macOS 10.15.4 (19E287)
| Before PR | After PR | After PR (narrow) | …

Prevent unnecessary truncation of the conversation header text

---

sticker-creator/store/ducks/stickers.ts

I currently have a sticker pack on Telegram which I cannot port to Signal because it has only two stickers. I don't see why we should arbitrarily require four stickers. I could also imagine a sticker pack with just one sticker in it, if that sticker is really good.

drop minimum sticker count to 1

---

ts/components/conversation/GroupNotification.stories.tsx
ts/components/conversation/GroupNotification.tsx

Fixes #4341 
Logic selecting the group notification for adding users was wrong.
NOTE: previous commit for this ticket (#205ee6c) did not fix the issue.
Added test to storybook and manually tested (with Polish translation as the task reported) on Windows 10 Home 64b

Group update notifications use incorrect string

---

main.js

Fixes: #4348 
I tested this manually on OSX by entering full screen mode and then pressing CMD + W to close the window. After the code addition, it minimizes then closes the window. I didn't add the return to full screen logic since other applications like Firefox don't do the same, but open to suggestions.

make sure closing window in fullscreen does not hang

---

about.html

Fixes #4205 
The CSS change prevents additional whitespace content on different devices to cause a scroll bar to be show. I replicated the issue screenshots by adding line breaks resulting in the same problem.
Note: I saw the previous PR to the other issue of the same nature. We don't need to set a fixed height and should just hide the extra whitespace instead.

make sure scroll is hidden on about page

---

js/views/conversation_view.js
ts/components/CompositionArea.tsx
ts/components/CompositionInput.tsx

Fixes #4332 
Use Escape to cancel "reply to": when focus is on the input and user is replying to a message (=a message is quoted), pressing Escape will unquote the message. The content of the input remains unchanged (ie. the input area is NOT cleared).
Manually tested on Win 10 Home x64.

Escape should close/cancel "reply to"

---

_locales/en/messages.json
js/background.js
js/notifications.js
js/settings_start.js
js/views/settings_view.js
main.js
preload.js
settings.html
settings_preload.js
ts/test/types/Settings_test.ts
ts/types/Settings.ts
ts/util/lint/exceptions.json

In many GNU/Linux setups, drawing attention when a notification arrives causes the Signal window to steal focus immediately and interrupt the user from what they were doing before the notification arrived. GNOME Shell is the most prominent example of this behavior, but there are likely other cases as well. Suddenly stealing focus on external events like this can even pose a security problem in some cases, e.g. if the user is in the middle of a typing a sudo password on one monitor while a notification arrives and focuses Signal on another monitor. See #4452 for more information.
Disabling attention drawing entirely for Linux is also problematic because some users rely on it as the sole indication of a new message, as seen in #3582 and #3611.
Commit f79069455932397105e025ef9bc04e74a9e6f612 …

Add setting to toggle notification attention drawing

---

ts/components/CompositionInput.tsx

For the `submit` block, Included a check for the `alt` key (i.e., `option` on macs). `alt` + `Enter` will defer to default platform keybindings.
Fixes #4352 
**Manual testing:**
Platform: macOS v. 10.14.5
Steps:
1. Launched desktop app
2. Opened "Note to Self" conversation
3. In the composition editor, pressed `option` + `Enter` to create newline

ISSUE-4352 -- Defer to default keybindings for `alt` + `enter`

---

stylesheets/_debugLog.scss

Fixes #4496 
Fix the "Copy" button text wrapping in the Debug Log form for localization.
Manual testing steps:
1. In `normalizeLocaleName` (`localize.js`), edit the return value to anything besides `en`. (I used `pl` for the first test.)
2. Launch the app
3. In the menu, go to `View->Debug Log` to launch the Debug Log dialog
4. Click Submit
5. View the "Copy" button in the form.
-------------------
-------------------
-------------------

ISSUE-4496 -- Fix debug log "Copy" button text wrapping for localization

---

main.js

* on macOS, in fullscreen mode, closing the about window caused the main window to remain in visibility hidden.
* The solution - set fullscreen off, show main window and set fullscreen on again (just showing main window wouldn't work).
Resolves: #4540
This commit solves the about page closing bug on macOS fullscreen mode:
Upon closing about page event, check if it's on full screen mode AND macOS (to avoid unnecessary results in other platforms) - and if so, perform exit of full screen mode, show the main window, and re-enter full screen mode.
Tested on OS Catalina 10.15.6 on both states (full screen, regular).

Bug fix escape 'about page' is breaking on fullscreen mode [macOS] (Issue #4540)

---

ts/textsecure/WebAPI.ts

Not sure if the omission of this argument sanity check is intentional, but if it is, it sure is inconsistent, and should be documented as such.

WebAPI.initialize: add missing validity check for proxyUrl

---

sticker-creator/preload.js
sticker-creator/store/ducks/stickers.ts

Animated stickers are allowed to be up to 300kB since bdd71e489859eb6c56434ad4b71663b3251b2e7c. However, a validation was still in place in `sticker-creator/store/ducks/stickers.ts`, preventing all stickers (APNG and Webp) to be above 100kB.
This commit fixes this, allowing to upload APNG stickers up to 300kB.
I'm not sure if this test can be removed altogether tho: https://github.com/signalapp/Signal-Desktop/blob/779487df017d8ff2db55cbda96f8fdf22f9415a7/sticker-creator/store/ducks/stickers.ts#L135-L138

Fix max size for animated stickers

---

ts/services/calling.ts

Fixes #4599. Straightforward fix, the video call flag just wasn't being checked. I verified after making the fix that audio call lobbies no longer automatically activate my webcam on startup, and that video call lobbies still activate it as expected. Tested on Ubuntu 20.04.1 LTS.

Don't enable webcam on audio call startup

---

_locales/en/messages.json
app/spell_check.js
preload.js
ts/components/Lightbox.tsx

Wire up context menu handlers to support copying attachment images to clipboard from lightbox view. This follows the behavior of Slack's desktop app pretty closely, except that I intentionally didn't include an option to copy the image URL.
This scratches a personal itch. I often use the Note to Self feature to send images between computers, and copying is usually a lot easier than downloading. Should go a long way toward addressing #3350.
- I didn't write any unit tests. I'm not sure how to automate this.
- I tested manually on Ubuntu 19.10. I verified that:
- No context menu appears for GIF images (NativeImage and Electron's clipboard API only supports PNG and JPEG).
- No context menu appears for videos.
- Messages with multiple attachments are handled correctly.
- Non-attachment images …

Add menu option for copying supported images in lightbox

---

ts/components/Lightbox.tsx

Reference: https://www.w3.org/Graphics/JPEG/
The lightbox copy menu wasn't showing for JPEG images because #4614 was checking incorrectly for "image/jpg". I've verified that this fixes the issue in my own testing.

Fix MIME check for JPEG in lightbox copy handler

---

CONTRIBUTING.md

The inclusion of the `git-lfs` requirement from #3927 applies to more operating systems than just macOS. Specifically, I just encountered this problem during setup on an Arch Linux machine. This moves the mention of the requirement out of the macOS-specific setup instructions and into the general Developer Setup section.

Move mention of git-lfs requirement to Developer Setup in contributor docs

---

ts/components/conversation/Linkify.tsx

This pull request changes EXACTLY 2 binary bits in the code, changing `now` to `how` since this was a comment typo.  
The fix took place in the `Linkify.tsx` file.

Fixed a comment typo in Linkify.tsx

---

ts/components/CompositionArea.tsx
ts/components/emoji/EmojiButton.tsx
ts/components/emoji/EmojiPicker.tsx

Added a new optional property to `EmojiButton`, this property (`onClose`) allows providing a callback which will be executed on emoji picker close, for example, for focusing back the `CompositionInput` after closing the emoji picker.
Also, removed the old focus approach (that worked only on `keypress`)
Fixes #4723, #4708
Tested on macOS (Big Sur), also tested the changes on storybook using chrome, brave and firefox.

Fix message input emoji focus close

---

ts/quill/emoji/completion.tsx

Fixes https://github.com/signalapp/Signal-Desktop/issues/4773
Updated the Regular Expression to also support detecting upper case combinations, This allows for users to type a capital letter after the colon key, and still get emoji results like so:
OS Information:
```
Darwin Jacobs-MacBook-Pro 20.3.0 Darwin Kernel Version 20.3.0: Mon Dec  7 22:04:02 PST 2020; root:xnu-7195.80.16.111.1~1/RELEASE_X86_64 x86_
```
I haven't performed any tests on any operating systems other than MacOS. I do not have access to any other machines at this time.
Signed-off-by: JPyke3 <pyke.jacob@pm.me>

Update emoji completion to be case insensitive

---

ts/state/ducks/search.ts

Allow hyphenated query (query including hyphen "-") on conversations and contacts search.
Fixes: #4707
Tested on macOS (Big Sur).

Allow hyphenated query on conversations and contacts search

---

main.js

When I open the settings menu the position will be fixed, independant where I moved the app window. On my multi screen layout this can be confusing when the settings open on the main screen although the main window is on another monitor − on big monitors this might be also strange. My change sets the position of the settings window right in the middle above the main window.

GUI: Open settings window centered above mainwindow

---

package.json

libappindicator1 has been deprecated by Debian\[0\] and will not be shipped from
Debian Bullseye on.
Fixes #4761.
[[0]](): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037
See https://github.com/signalapp/Signal-Desktop/issues/4761#issuecomment-780178017 for more details.
~~I'm still trying thing out and see if there's anything missing.~~
Update:
Everything is working (including tray icon) on a Debian with no package containing 'libappindicator' or 'libayatana' (supposed to be the replacement) installed. There might be a dependency required to make this work which was just preinstalled on the system I used (a fresh VM on Xfce), but it's hard to guess like this.
According to https://www.electronjs.org/docs/api/tray:
```
On Linux distributions that only have app indicator support, …
```

Remove Debian dependency libappindicator1

---

app/sql_channel.js
stylesheets/_modules.scss
ts/linkPreviews/linkPreviewFetch.ts
ts/models/conversations.ts
ts/models/messages.ts
ts/sql/Queueing.ts
ts/test-electron/linkPreviews/linkPreviewFetch_test.ts
ts/textsecure/MessageReceiver.ts
ts/textsecure/Storage.ts
ts/textsecure/SyncRequest.ts
ts/util/getAnimatedPngDataIfExists.ts
ts/util/windowsZoneIdentifier.ts
ts/window.d.ts

Fixes typos in source code files found by [Fossies source code check](https://fossies.org/linux/test/Signal-Desktop-development.3324563.210327.tar.gz/codespell.html)
Evan asked me to:
- fix all of the errors in the ts/ directory, except for exceptions.json
- fix the one typo in stylesheets/_modules.scss. "tht" should be "the"
- don't fix any of the errors in any of the other folders yet (ignore test/, libtextsecure/, js/, and app/)

Fix typos in ts files as per Fossies source code check

---

_locales/en/messages.json

The node tests have 5 errors in the most recent sources.
Fixes #5060 
I changed the text of a warning message when deleting a message to clarify that it will be only deleted from the currently used device.
The change was tested on macOS 10.15.7:

Clarify warning text for local message deletion #5060

---

ts/test-both/util/cleanSearchTerm_test.ts
ts/util/cleanSearchTerm.ts

This addresses the bug reported in this issue  #5015 where a backslash entered in the search box along with another non-whitespace character caused the loading to never terminate.
I added '\\' to the regex that filters out special characters from search terms and added a test for this case.

remove backslash from search queries.

---

ts/test-both/util/getInitials_test.ts
ts/util/getInitials.ts

https://github.com/signalapp/Signal-Desktop/issues/4172
I made changes to the `getInitials` method to handle more cases. The first letter of the first and the last word in a passed string will form the initials. Any non-letters, suffixes such as "Jr", "Sr" or Roman numerals will be omitted.
I added tests and tried to cover multiple edge cases.
OS X 10.15.6.

getInitials: handle more cases to reduce cross-platform inconsistencies

---

ts/services/calling.ts

The group call update message after starting a group call is currently only
sent in the `onLocalDeviceStateChanged` callback. But often the peekInfo is
not available yet when the connection state changes to Joined, effectively
preventing the group call update message to be sent.
This commit also sends the message in the `onPeekChanged` callback. It is still
only sent at most once, which is ensured by the updateMessageState check.
I'm not sure if ringrtc is behaving correctly here or if the peek info should always be available if the connection state is Joined.
Then this PR would be just a workaround for an underlying problem in ringrtc ...
Fixes #4915
Manually tested with Signal-Desktop on Linux (x86_64) and the Android app.

Fix race condition which often prevented sending group call started message

---

ts/linkPreviews/linkPreviewFetch.ts
ts/test-electron/linkPreviews/linkPreviewFetch_test.ts

Fixes #4977. I added a new test since none existed that tested the order in which preview images are prioritized. I only tested on Arch Linux.
I'm open to any and all feedback!
Before:
After:

High resolution link preview images

---

ts/components/CallingPip.tsx

Fixes PiP sliding down on click when snapping to left or right side during call
The PiP's top margin was added to the translate y position which resulted in moving it down by that margin on every mouse up, when snapping to the left or right side of the window.

Fix pip sliding down on click

---

stylesheets/_modules.scss

Fixes #5090 .
I needed to adjust a width calculation by one pixel because fractional values were causing the filename to truncated even when it was short.
I tested this on Arch Linux (kernel version 5.11.8-arch1-1).
Before:
After:

fix attachment filename being truncated when zoomed in

---

stylesheets/_modules.scss

Reduced the min-width/increased the max-width of media queries to switch sooner from reaction icons for messages to a "more" menu.
Smallest media query
next smallest media query

Fix cropped message reaction icons

---

package.json
ts/util/lint/exceptions.json
yarn.lock

The currently pinned version of `node-gyp` requires Python 2.  Python 2
has reached its EOL a long time ago and is unsupported by upstream.
The requirement on Python 2 is also an unnecessary barrier for new
developers to contribute to Signal.
This changeset updates the required version of node-gyp to one
compatible with Python 3.
`CONTRIBUTING.md` remains unchanged, since this dependency was not
previously mentioned anyway.
Supersedes #4407
Fixes #4783

Use a node-gyp version which supports Python3

---

ts/state/ducks/search.ts

Fixes #5137
See issue.
Sanitizing the query can lead to an empty query, which hangs the search. We return early if the query is empty after sanitization.

Do not search if normalized query is empty

---

ts/state/selectors/search.ts
ts/test-both/state/selectors/search_test.ts

Fixes #5158.
See issue.
I don't think that's the proper way to address this issue, but it seems to work in practice. Feel free to close this PR in favor of a better fix.
If I note:
M(e)
G(roup)
O(ther)
I have tested these cases and the header seems correct (message sent from - to):
O - G
O - M
M - G
M - O
M - M (notes to self)

Fix 1:1 message to/from in search results

---

background.html
test/index.html

There were two unquoted attribute values in the `background.html` templates, this changes them to being quoted. I don't believe it was having any functional effect, but it was causing problems for syntax highlighting in editors, and they should be quoted to match the rest of the file.

Quote HTML attribute values in template

---

ts/views/conversation_view.ts

There was a typo in the method name which would be invoked on a change event, which would probably lead to an error at run-time, and broken functionality.
I'm new to the codebase, so not sure what this would affect, and I didn't see any tests that covered `conversation_view.ts` to extend. I ran `yarn ready` and it passes, that's all I've got for testing.
The typo was spotted with a spell checker, rather than noticing any functional problems.

Fix typo in method name

---

background.html
test/index.html

The window is currently not draggable on MacOS during initial setup. This fixes that by adding the `module-title-bar-drag-area` div to those views.

Make window draggable on MacOS during device setup

---

ts/components/conversation/Message.tsx

- [] My changes are [rebased](https://medium.freecodecamp.org/git-rebase-and-the-golden-rule-explained-70715eccc372) on the latest [`development`](https://github.com/signalapp/Signal-Desktop/tree/development) branch
- [] A `yarn ready` run passes successfully ([more about tests here](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md#tests))
Fixes #5397 
I have fixed the issue of HTML encoded entities not being unescaped in description link preview. 
I have used unescape method of lodash.
Before:
After:
I have tested if the same issue happens with the title also. But it seems like it happens only for the description of the preview.

Unescape HTML encoded entities in link preview

---

ts/components/emoji/EmojiPicker.tsx

When the emoji picker was opened, pressing the Ctrl-key would close it. Because of that, the zoom in/out accessibility features couldn't be used at that time. With this commit, the Ctrl-key will no longer trigger the closing of the emoji picker.
Tested on Windows 10* 64-bit, manually by using the emoji picker both before and after the changes to test if the change indeed fixes the issue whilst not causing any new issues.
Fixes #5062.

Don't close emoji picker when Ctrl key is pressed (resolves #5062)

---

stylesheets/_modules.scss
ts/components/conversation/media-gallery/MediaGridItem.tsx

Fixes #5241
The Conversation Media List and the Media Gallery lay out their items slightly differently:
* In the Conversation Media List, the available width is divided into 6 equally sized containers for thumbnails
* In the Media Gallery, each thumbnail is a fixed width (94px)
The existing styling fixed the width of the media grid item to 94px as well, but this no longer works for the Conversation Media List as the width of its thumbnails can exceed 94px as the viewport is made wider.
A simple change to the media grid item image styling to go from a fixed with to 100% instead.
Also removes some duplicative styling to help make maintenance of this simpler.
Environment: WSL
Standard tests run as per guidelines:
```
[test-node    ]   841 passing (4s)
[test-node    ]   4 pending
[test-node …
```

Allow media grid item images to fill container

---

ts/quill/emoji/completion.tsx
ts/quill/util.ts

Fixes #5018.
Alternative to #5156.
See issue.

Make emoji/text match case insensitive (alternative implementation)

---

ts/components/conversation/Quote.stories.tsx

Commit edab7c7d83e6f8478d0638636bbdc44e69599e54 introduced this small error, so spinning this into a tiny PR per random conversation in #5639.
Fixing a tyop. Not testing, it's buried in a string and not referenced elsewhere.

fix action typo

---

ts/components/CompositionArea.tsx
ts/components/LeftPane.tsx
ts/components/emoji/EmojiButton.tsx
ts/components/leftPane/LeftPaneArchiveHelper.tsx
ts/components/leftPane/handleKeydownForSearch.ts
ts/components/stickers/StickerButton.tsx

This PR addresses #5837. I did manual testing of all shortcuts described in `Help -> Show Keyboard Shortcuts` with RU keyboard layout and fixed ones that did not work. Tests were perfomed in `Linux pc 5.16.16-zen1-1-zen`

Fix several shortcuts not working with non-EN keyboard layouts

---

stylesheets/components/Lightbox.scss

*Some unrelated timestamp tests seem to fail on windows with a german locale*
Reduce the size of the zoom button to the dimensions of the image. Set its height to `fit-content` and add an equal margin to the top and bottom to keep the image centered.
Fixes #5586

fix: reduce zoom button size to image dimensions

---

ts/state/ducks/composer.ts

Fixes #6284 - does not focus immediately (so as to avoid stealing
focus) and does not focus if the file browser is cancelled.
Since there is no Send button, this makes it easier and reduces frustration when adding attachments.
Currently a user must manually click on the text input box or shift-tab to focus it and then press Enter to send.
This change automatically focuses the text input box if an attachment has been added, allowing users to just press Enter.
Manually tested on Ubuntu 22 64-bit / Gnome. No new tests since I can't find good examples of tests for
similarly small UX-related changes, though I'm happy to do so.

Focus the text input box after successfully attaching a file

---

ts/components/conversation/Message.tsx

Fixes #6282, as double-clicking the reaction "box" no longer will create a draft reply. This fix simply disables the replyToMessage action if the double click takes place within the reaction reactions DOM, as if the user is double clicking in this area it is almost always with the intention of dismissing the reaction window.
Manual testing was done to ensure that this behavior not only fixed the double clicking issue within the reactions DOM, but to ensure reply functionality was not affected outside the DOM. Everything functioned as expected.
Cheers!

Double clicking emoji reaction no longer brings up replies

---

ts/components/LeftPane.stories.tsx
ts/components/leftPane/LeftPaneInboxHelper.tsx
ts/state/ducks/search.ts
ts/state/selectors/search.ts
ts/state/smart/LeftPane.tsx
ts/test-both/state/selectors/search_test.ts
ts/test-node/components/leftPane/LeftPaneInboxHelper_test.tsx

Fixes #6281
This PR fixes Cmd+f/Ctrl+f functionality in the left pane. Using a keyboard to search across all
conversations should now automatically change the left pane width to accommodate the search input component.
I made an assumption that when a user searches globally, the behavior of the left pane should be similar to when a user searches within a single conversation.
To do so, I chose to create a new value in state called `globalSearch`. I'm not super happy with the name, but I don't have any better ideas. Another approach that seems to work and avoids adding a new value in state would be to assign any string to `searchConversationId` that doesn't match a real conversation, e.g. `searchConversationId: 'global'`, but that seemed less clear than having a dedicated variable. …

Fix keyboard search when left pane is narrow

---

ts/background.ts

Fixes #6214 
This PR allows showing the shortcut guide when pressing ctrl+/ without also allowing ctrl+alt+/.

Disable ctrl+alt+/ from showing shortcut guide

---

ts/quill/signal-clipboard/index.ts

Fixes #6315. If there is no selection when a copy action is executed, there will be no overwriting of the clipboard. Manual testing was done to ensure that copying functionality was otherwise unaffected including successful the copying & pasting of white space. Cheers!

Fixed empty copying overwriting clipboard

---

stylesheets/components/LeftPaneSearchInput.scss

In the process of reducing avatar sizes (3a246656e3dc3b9b01d3c0a162a23a423afee43b), the vertical centering of the conversation pill (chip) in the search input was broken. This PR restore conversation pill vertical centering by correcting corresponding `bottom` and `top` CSS properties.
Before the fix:
After the fix:

Fix alignment of the conversation pill in search input

---

CONTRIBUTING.md

The existing instructions help us to create multiple additional storage profiles with `NODE_APP_INSTANCE.` However, it was not immediately clear where to find the `config` directory, as there is a config.json in `userData,` and for Linux the data directory is in `.config.` Therefore, some minor adjustments can clarify potential points of confusion.

Clarify directory for additional storage profiles

---

ts/components/conversation/Message.tsx
ts/components/conversation/MessageMetadata.tsx
ts/util/lint/exceptions.json

Fixes #6428
I'm not sure if the code should exist somewhere else, if so I can move it.
I'm not sure if triple-clicking is a macOS specific functionality or not.  If it is, a check can be added to only enable this change for macOS devices.
Can be tested by opening a conversation and triple-clicking a message.  All text up to the next line break in the message should be selected.  It can then be copied and pasted with only the message text, the timestamp should not be copied or pasted.
I didn't find any existing tests to go off of for the `Message` component, so I didn't write any new tests.
Tested on macOS 13.4.1 (22F82).
https://github.com/signalapp/Signal-Desktop/assets/52075362/a6e69298-4201-4c1d-abaf-6dc2b3049651

Only select message data on triple click

---

package.json

I checked out this repo onto my machine, running macOS 13.2.1.
I noticed `yarn test-node` is failing.
For `yarn test-node`, the tests were failing when comparing timestamps, expecting `3:56 AM`.
I ran `locale` in my terminal and found my locale is `en-CA.UTF-8`.
After forcing `LANG=en-us` when running `yarn test-node`, the test passes.
I believe this also fixes these issue #5832 and PR #6210.

Fix timestamp tests failing on non-US locale machines

---

ts/components/StoryListItem.tsx

The official badge CSS element was moved from StoryListItems.scss to ContactModal.scss. The change wasn't reflected in this file, and so the badge did not appear when opening Stories for the first time. I updated the file so that the badge shows up again.

make the offical badge appear when opening stories for the first time

---

ts/components/DeleteMessagesModal.tsx
ts/util/sendDeleteForEveryoneMessage.ts

Fixes #6682. This ensures that 'Note To Self' messages can be deleted from all devices at any time as opposed to being constrained to the one day time box as messages to other Signal users are. This reflects the behavior that is seen on other Signal clients.
This fix was manually tested on a Fedora 38 workstation. I attempted to remove old messages in 'Note To Self', ensured the proper prompts were given, and that these message deletions were reflected on my Android Signal client. I also checked with conversations to other Signal users and ensured that the previous functionality was unchanged.
Let me know if there's any critiques, cheers!

Always allow 'Note To Self' deletions regardless of time

---

config/default.json
config/production.json

Currently, the staging builds (including the official ones for [Public Username Testing (Staging Environment)](https://community.signalusers.org/t/56866)) use the production SFU by default.
The production (or the `test`) SFU doesn't work (i.e. group calls are cancelled immediately) in the staging environment (because of different ZK parameters, I believe), requiring manually changing the SFU url via `SignalDebug.setSfuUrl` to the staging SFU.
This PR changes the default SFU for builds to the staging SFU, overriding it with the production SFU only for production builds.
With this PR, Desktop's behavior aligns with [Signal Android](https://github.com/signalapp/Signal-Android/blob/19e726a630c1f0aa681cd4e771f01ce5bb0b4148/app/src/main/java/org/thoughtcrime/securesms/util/Environment.kt#L29-L31 …

Default to staging SFU for non-production builds

---

ts/components/CompositionInput.tsx
ts/quill/auto-substitute-ascii-emojis/index.tsx

Re #1389 
Closes #4942
Testing was done manually. If sensible, I can add automated tests for this feature.

feat(input): added ascii to emoji conversion

---

ts/components/Lightbox.tsx

This commit will allow to save images from a gallery view by pressing Enter, 's', or 'd' keys.
To test:
- Open a conversation containing 10+ images attached to a single message.
- Click on the first image, an image gallery will open.
- Press 'Enter' to download the first image.
- Press 'Right' then 'Enter' to download subsequent images.
- This improves accessibility - no need to right-click on every image and select 'Download' from the popup menu.

Save current image from the gallery view by pressing 's', 'd', or 'Enter'

---

stylesheets/_mixins.scss

Hello,
There is a simple feature request for Desktop app with good Urdu fonts support. On the Desktop app the font for Urdu language is not good enough. Choosing a better font at least will be a great feature. It's very much related to PR but with Urdu fonts instead of Persian fonts https://github.com/signalapp/Signal-Desktop/pull/6688
It started here https://community.signalusers.org/t/good-urdu-fonts-support/58124

Good Urdu Fonts Support

---

README.md

This PR fixes the copyright year in the README. Currently the copyright year is 2013, whereas the Android and iOS repos show their copyright year as 201X-202X.

Fix README copyright year

---

ts/Bytes.ts
ts/context/Bytes.ts
ts/state/selectors/items.ts
ts/test-mock/pnp/username_test.ts

Changes the base64 encoding used for encrypted username links (`https://signal.me/#eu/<encrypted username>`) from base64 to base64url encoding to match Android and iOS behavior. (https://community.signalusers.org/t/beta-feedback-for-the-upcoming-desktop-7-3-release/59611/4?u=bjoel)

Use base64url encoding for encrypted username

---

stylesheets/components/NavSidebar.scss
ts/components/CallsTab.tsx
ts/components/ContextMenu.tsx
ts/components/LeftPane.tsx
ts/components/NavSidebar.tsx
ts/components/NavTabs.tsx
ts/components/SendStoryModal.tsx
ts/components/StoriesTab.tsx
ts/components/StoryViewsNRepliesModal.tsx

Fix for a minor annoyance I had with the behaviour of the context menu at the top of the left pane. Most other menu buttons throughout the app are toggles, i.e., they show the menu on the first click and hide it on the next click. These menu buttons weren't toggles and I'd find myself clicking once to show, then a second time to hide, but the menu wouldn't go away. The buttons at the top of the left pane were also missing active states, unlike most other similar buttons including the hamburger menu.
https://github.com/signalapp/Signal-Desktop/assets/1466970/5f5bb024-4aa0-4737-a4ef-61718bf563a4
No change to the behaviour of the menus in the conversation pane (just showed them in the demo for reference). The new behaviour is just for the triple dot menu in the left pane.
- Refactored …

Toggle context menus on click and add active state

---

ts/components/ToastManager.stories.tsx
ts/components/ToastManager.tsx
ts/state/ducks/conversations.ts
ts/types/Toast.tsx

Fixes #6968 following [these pointers](https://github.com/signalapp/Signal-Desktop/issues/6968#issuecomment-2274299133). If you archive a pinned conversation, then undo that, with this change, the conversation will be pinned again.
I tested it manually using the standalone setup, on Fedora Silverblue Linux 40. I couldn't find which files would contain tests for the files I touched, but could look at writing some tests with some pointers.

Re-pin a conversation after undoing archival
